// Curated operator copy for the Audit Operations Console.
// Canonical action, outcome, actor and target codes intentionally remain protocol values.

const AUDIT_KEYS = [
    'audit.observability',
    'audit.title',
    'audit.description',
    'audit.export_jsonl',
    'audit.export_csv',
    'audit.refresh',
    'audit.filters',
    'audit.filters_description',
    'audit.action',
    'audit.outcome',
    'audit.all',
    'audit.actor_type',
    'audit.target_type',
    'audit.request_id',
    'audit.actor_fingerprint',
    'audit.target_fingerprint',
    'audit.after',
    'audit.before',
    'audit.page_size',
    'audit.apply',
    'audit.clear',
    'audit.safe_filter_hint',
    'audit.events',
    'audit.previous',
    'audit.page',
    'audit.next',
    'audit.retention',
    'audit.retention_description',
    'audit.retention_days',
    'audit.max_events',
    'audit.save_retention',
    'audit.details',
    'audit.close',
    'audit.occurred_at',
    'audit.event_id',
    'audit.change_codes',
    'audit.copy_request',
    'audit.pivot_request',
    'audit.unknown',
    'audit.empty',
    'audit.loading',
    'audit.load_failed',
    'audit.invalid_range',
    'audit.copied',
    'audit.copy_failed',
    'audit.exporting',
    'audit.exported',
    'audit.export_failed',
    'audit.retention_confirm',
    'audit.retention_updated',
    'audit.update_failed',
];

const AUDIT_LOCALE_VALUES = {
    en: ["Observability","Audit events","Investigate every management mutation through redacted, durable evidence.","Export JSONL","Export CSV","Refresh","Filters","Narrow the durable event stream by canonical audit fields.","Action","Outcome","All","Actor type","Target type","Request ID","Actor fingerprint","Target fingerprint","Occurred after","Occurred before","Events per page","Apply filters","Clear","Only category filters and page size are remembered. Correlating identifiers and time bounds remain session-only.","Event stream","Previous","Page {page}","Next","Retention policy","Events are pruned when either the age or count limit is exceeded.","Retention days","Maximum events","Save retention","Event details","Close","Occurred at","Event ID","Change codes","Copy request ID","Filter by request ID","Unknown","No audit events match these filters.","Loading audit events…","Audit events could not be loaded.","The filter values or time range are invalid.","Request ID copied.","Request ID could not be copied.","Preparing bounded export…","Audit export downloaded.","Audit export could not be completed.","Save {days} days and {maxEvents} events? Events outside either limit may be removed immediately.","Retention saved. {count} events were removed.","Retention policy could not be updated."],
    'zh-CN': ["可观测性","审计事件","通过脱敏且持久的证据调查每一次管理变更。","导出 JSONL","导出 CSV","刷新","筛选器","按规范审计字段缩小持久事件流。","操作","结果","全部","操作者类型","目标类型","请求 ID","操作者指纹","目标指纹","发生时间晚于","发生时间早于","每页事件数","应用筛选器","清除","仅记住类别筛选器和每页数量。关联标识符与时间范围仅在本次会话中保留。","事件流","上一页","第 {page} 页","下一页","保留策略","事件会在超过时间或数量上限时被清理。","保留天数","最大事件数","保存保留策略","事件详情","关闭","发生时间","事件 ID","变更代码","复制请求 ID","按请求 ID 筛选","未知","没有符合这些筛选器的审计事件。","正在加载审计事件…","无法加载审计事件。","筛选值或时间范围无效。","已复制请求 ID。","无法复制请求 ID。","正在准备有界导出…","审计导出已下载。","无法完成审计导出。","保存 {days} 天和 {maxEvents} 个事件吗？超出任一限制的事件可能会立即删除。","保留策略已保存，删除了 {count} 个事件。","无法更新保留策略。"],
    'zh-TW': ["可觀測性","稽核事件","透過已遮蔽且持久的證據調查每一次管理變更。","匯出 JSONL","匯出 CSV","重新整理","篩選器","依標準稽核欄位縮小持久事件串流。","操作","結果","全部","操作者類型","目標類型","請求 ID","操作者指紋","目標指紋","發生時間晚於","發生時間早於","每頁事件數","套用篩選器","清除","只會記住類別篩選器與每頁數量。關聯識別碼和時間範圍僅保留於本次工作階段。","事件串流","上一頁","第 {page} 頁","下一頁","保留政策","事件會在超過時間或數量上限時清除。","保留天數","事件數上限","儲存保留政策","事件詳細資料","關閉","發生時間","事件 ID","變更代碼","複製請求 ID","依請求 ID 篩選","未知","沒有符合這些篩選器的稽核事件。","正在載入稽核事件…","無法載入稽核事件。","篩選值或時間範圍無效。","已複製請求 ID。","無法複製請求 ID。","正在準備有限匯出…","稽核匯出已下載。","無法完成稽核匯出。","要儲存 {days} 天與 {maxEvents} 個事件嗎？超出任一限制的事件可能會立即移除。","保留政策已儲存，已移除 {count} 個事件。","無法更新保留政策。"],
    de: ["Observability","Audit-Ereignisse","Untersuchen Sie jede Verwaltungsänderung anhand redigierter, dauerhaft gespeicherter Nachweise.","JSONL exportieren","CSV exportieren","Aktualisieren","Filter","Den dauerhaften Ereignisstrom nach kanonischen Audit-Feldern eingrenzen.","Aktion","Ergebnis","Alle","Akteurstyp","Zieltyp","Anfrage-ID","Akteur-Fingerabdruck","Ziel-Fingerabdruck","Aufgetreten nach","Aufgetreten vor","Ereignisse pro Seite","Filter anwenden","Leeren","Nur Kategoriefilter und Seitengröße werden gespeichert. Korrelationskennungen und Zeitgrenzen bleiben sitzungsbezogen.","Ereignisstrom","Zurück","Seite {page}","Weiter","Aufbewahrungsrichtlinie","Ereignisse werden bereinigt, sobald die Alters- oder Anzahlgrenze überschritten ist.","Aufbewahrungstage","Maximale Ereignisse","Aufbewahrung speichern","Ereignisdetails","Schließen","Aufgetreten um","Ereignis-ID","Änderungscodes","Anfrage-ID kopieren","Nach Anfrage-ID filtern","Unbekannt","Keine Audit-Ereignisse entsprechen diesen Filtern.","Audit-Ereignisse werden geladen…","Audit-Ereignisse konnten nicht geladen werden.","Filterwerte oder Zeitraum sind ungültig.","Anfrage-ID kopiert.","Anfrage-ID konnte nicht kopiert werden.","Begrenzter Export wird vorbereitet…","Audit-Export heruntergeladen.","Audit-Export konnte nicht abgeschlossen werden.","{days} Tage und {maxEvents} Ereignisse speichern? Ereignisse außerhalb einer Grenze können sofort entfernt werden.","Aufbewahrung gespeichert. {count} Ereignisse wurden entfernt.","Aufbewahrungsrichtlinie konnte nicht aktualisiert werden."],
    es: ["Observabilidad","Eventos de auditoría","Investiga cada cambio administrativo mediante evidencia redactada y duradera.","Exportar JSONL","Exportar CSV","Actualizar","Filtros","Acota el flujo de eventos duradero mediante campos de auditoría canónicos.","Acción","Resultado","Todos","Tipo de actor","Tipo de objetivo","ID de solicitud","Huella del actor","Huella del objetivo","Ocurrido después de","Ocurrido antes de","Eventos por página","Aplicar filtros","Limpiar","Solo se recuerdan los filtros de categoría y el tamaño de página. Los identificadores de correlación y los límites de tiempo quedan en la sesión.","Flujo de eventos","Anterior","Página {page}","Siguiente","Política de retención","Los eventos se eliminan cuando se supera el límite de antigüedad o de cantidad.","Días de retención","Máximo de eventos","Guardar retención","Detalles del evento","Cerrar","Fecha del evento","ID del evento","Códigos de cambio","Copiar ID de solicitud","Filtrar por ID de solicitud","Desconocido","Ningún evento de auditoría coincide con estos filtros.","Cargando eventos de auditoría…","No se pudieron cargar los eventos de auditoría.","Los filtros o el intervalo de tiempo no son válidos.","ID de solicitud copiado.","No se pudo copiar el ID de solicitud.","Preparando exportación limitada…","Exportación de auditoría descargada.","No se pudo completar la exportación de auditoría.","¿Guardar {days} días y {maxEvents} eventos? Los eventos fuera de cualquier límite pueden eliminarse de inmediato.","Retención guardada. Se eliminaron {count} eventos.","No se pudo actualizar la política de retención."],
    fr: ["Observabilité","Événements d’audit","Examinez chaque mutation d’administration grâce à des preuves expurgées et durables.","Exporter en JSONL","Exporter en CSV","Actualiser","Filtres","Affinez le flux d’événements durable avec les champs d’audit canoniques.","Action","Résultat","Tous","Type d’acteur","Type de cible","ID de requête","Empreinte de l’acteur","Empreinte de la cible","Survenu après","Survenu avant","Événements par page","Appliquer les filtres","Effacer","Seuls les filtres de catégorie et la taille de page sont mémorisés. Les identifiants de corrélation et les bornes temporelles restent limités à la session.","Flux d’événements","Précédent","Page {page}","Suivant","Politique de conservation","Les événements sont purgés lorsque la limite d’âge ou de nombre est dépassée.","Jours de conservation","Nombre maximal d’événements","Enregistrer la conservation","Détails de l’événement","Fermer","Date de survenue","ID de l’événement","Codes de modification","Copier l’ID de requête","Filtrer par ID de requête","Inconnu","Aucun événement d’audit ne correspond à ces filtres.","Chargement des événements d’audit…","Impossible de charger les événements d’audit.","Les filtres ou la période sont invalides.","ID de requête copié.","Impossible de copier l’ID de requête.","Préparation de l’export limité…","Export d’audit téléchargé.","Impossible de terminer l’export d’audit.","Enregistrer {days} jours et {maxEvents} événements ? Les événements hors de l’une des limites peuvent être supprimés immédiatement.","Conservation enregistrée. {count} événements ont été supprimés.","Impossible de mettre à jour la politique de conservation."],
    id: ["Observabilitas","Peristiwa audit","Selidiki setiap perubahan pengelolaan melalui bukti tersensor yang tahan lama.","Ekspor JSONL","Ekspor CSV","Muat ulang","Filter","Persempit aliran peristiwa tahan lama berdasarkan bidang audit kanonis.","Tindakan","Hasil","Semua","Jenis pelaku","Jenis target","ID permintaan","Sidik jari pelaku","Sidik jari target","Terjadi setelah","Terjadi sebelum","Peristiwa per halaman","Terapkan filter","Hapus","Hanya filter kategori dan ukuran halaman yang diingat. Pengenal korelasi dan batas waktu hanya berlaku selama sesi.","Aliran peristiwa","Sebelumnya","Halaman {page}","Berikutnya","Kebijakan retensi","Peristiwa dipangkas saat batas usia atau jumlah terlampaui.","Hari retensi","Peristiwa maksimum","Simpan retensi","Detail peristiwa","Tutup","Waktu kejadian","ID peristiwa","Kode perubahan","Salin ID permintaan","Filter menurut ID permintaan","Tidak diketahui","Tidak ada peristiwa audit yang cocok dengan filter ini.","Memuat peristiwa audit…","Peristiwa audit tidak dapat dimuat.","Nilai filter atau rentang waktu tidak valid.","ID permintaan disalin.","ID permintaan tidak dapat disalin.","Menyiapkan ekspor terbatas…","Ekspor audit telah diunduh.","Ekspor audit tidak dapat diselesaikan.","Simpan {days} hari dan {maxEvents} peristiwa? Peristiwa di luar salah satu batas dapat langsung dihapus.","Retensi disimpan. {count} peristiwa dihapus.","Kebijakan retensi tidak dapat diperbarui."],
    it: ["Osservabilità","Eventi di audit","Esamina ogni modifica amministrativa tramite prove oscurate e persistenti.","Esporta JSONL","Esporta CSV","Aggiorna","Filtri","Restringi il flusso persistente tramite i campi di audit canonici.","Azione","Esito","Tutti","Tipo di attore","Tipo di destinazione","ID richiesta","Impronta attore","Impronta destinazione","Avvenuto dopo","Avvenuto prima","Eventi per pagina","Applica filtri","Cancella","Vengono ricordati solo i filtri di categoria e la dimensione della pagina. Identificatori di correlazione e limiti temporali restano nella sessione.","Flusso eventi","Precedente","Pagina {page}","Successiva","Criterio di conservazione","Gli eventi vengono eliminati quando si supera il limite di età o di quantità.","Giorni di conservazione","Numero massimo di eventi","Salva conservazione","Dettagli evento","Chiudi","Data e ora","ID evento","Codici di modifica","Copia ID richiesta","Filtra per ID richiesta","Sconosciuto","Nessun evento di audit corrisponde a questi filtri.","Caricamento eventi di audit…","Impossibile caricare gli eventi di audit.","I filtri o l’intervallo temporale non sono validi.","ID richiesta copiato.","Impossibile copiare l’ID richiesta.","Preparazione esportazione limitata…","Esportazione audit scaricata.","Impossibile completare l’esportazione audit.","Salvare {days} giorni e {maxEvents} eventi? Gli eventi oltre uno dei limiti possono essere rimossi subito.","Conservazione salvata. Rimossi {count} eventi.","Impossibile aggiornare il criterio di conservazione."],
    ja: ["オブザーバビリティ","監査イベント","マスキング済みの永続的な証跡から、すべての管理変更を調査します。","JSONL をエクスポート","CSV をエクスポート","更新","フィルター","正規の監査フィールドで永続イベントストリームを絞り込みます。","アクション","結果","すべて","実行者タイプ","対象タイプ","リクエスト ID","実行者フィンガープリント","対象フィンガープリント","この日時以降","この日時以前","1 ページのイベント数","フィルターを適用","クリア","記憶されるのはカテゴリフィルターとページサイズだけです。相関識別子と期間はセッション内にのみ保持されます。","イベントストリーム","前へ","ページ {page}","次へ","保持ポリシー","経過日数または件数の上限を超えたイベントは削除されます。","保持日数","最大イベント数","保持設定を保存","イベント詳細","閉じる","発生日時","イベント ID","変更コード","リクエスト ID をコピー","リクエスト ID で絞り込む","不明","このフィルターに一致する監査イベントはありません。","監査イベントを読み込み中…","監査イベントを読み込めませんでした。","フィルター値または期間が無効です。","リクエスト ID をコピーしました。","リクエスト ID をコピーできませんでした。","制限付きエクスポートを準備中…","監査エクスポートをダウンロードしました。","監査エクスポートを完了できませんでした。","{days} 日、{maxEvents} 件で保存しますか？いずれかの上限を超えたイベントは直ちに削除される場合があります。","保持設定を保存しました。{count} 件のイベントを削除しました。","保持ポリシーを更新できませんでした。"],
    ko: ["관측성","감사 이벤트","마스킹된 영구 증거를 통해 모든 관리 변경을 조사합니다.","JSONL 내보내기","CSV 내보내기","새로 고침","필터","표준 감사 필드로 영구 이벤트 스트림을 좁힙니다.","작업","결과","전체","행위자 유형","대상 유형","요청 ID","행위자 지문","대상 지문","이후 발생","이전 발생","페이지당 이벤트","필터 적용","지우기","범주 필터와 페이지 크기만 기억됩니다. 상관 식별자와 시간 범위는 세션에만 유지됩니다.","이벤트 스트림","이전","페이지 {page}","다음","보존 정책","기간 또는 개수 제한을 넘으면 이벤트가 정리됩니다.","보존 일수","최대 이벤트 수","보존 정책 저장","이벤트 세부 정보","닫기","발생 시각","이벤트 ID","변경 코드","요청 ID 복사","요청 ID로 필터링","알 수 없음","이 필터와 일치하는 감사 이벤트가 없습니다.","감사 이벤트 로드 중…","감사 이벤트를 불러올 수 없습니다.","필터 값 또는 시간 범위가 잘못되었습니다.","요청 ID를 복사했습니다.","요청 ID를 복사할 수 없습니다.","제한된 내보내기 준비 중…","감사 내보내기를 다운로드했습니다.","감사 내보내기를 완료할 수 없습니다.","{days}일 및 {maxEvents}개 이벤트로 저장할까요? 한도를 벗어난 이벤트는 즉시 제거될 수 있습니다.","보존 정책을 저장했습니다. {count}개 이벤트를 제거했습니다.","보존 정책을 업데이트할 수 없습니다."],
    pt: ["Observabilidade","Eventos de auditoria","Investigue cada alteração administrativa por meio de evidências ocultadas e duráveis.","Exportar JSONL","Exportar CSV","Atualizar","Filtros","Restrinja o fluxo durável pelos campos canônicos de auditoria.","Ação","Resultado","Todos","Tipo de ator","Tipo de destino","ID da solicitação","Impressão digital do ator","Impressão digital do destino","Ocorrido após","Ocorrido antes","Eventos por página","Aplicar filtros","Limpar","Apenas filtros de categoria e tamanho da página são lembrados. Identificadores de correlação e limites de tempo ficam somente na sessão.","Fluxo de eventos","Anterior","Página {page}","Próxima","Política de retenção","Os eventos são removidos quando o limite de idade ou quantidade é excedido.","Dias de retenção","Máximo de eventos","Salvar retenção","Detalhes do evento","Fechar","Ocorrido em","ID do evento","Códigos de alteração","Copiar ID da solicitação","Filtrar pelo ID da solicitação","Desconhecido","Nenhum evento de auditoria corresponde a estes filtros.","Carregando eventos de auditoria…","Não foi possível carregar os eventos de auditoria.","Os filtros ou o intervalo de tempo são inválidos.","ID da solicitação copiado.","Não foi possível copiar o ID da solicitação.","Preparando exportação limitada…","Exportação de auditoria baixada.","Não foi possível concluir a exportação de auditoria.","Salvar {days} dias e {maxEvents} eventos? Eventos fora de qualquer limite podem ser removidos imediatamente.","Retenção salva. {count} eventos foram removidos.","Não foi possível atualizar a política de retenção."],
    ru: ["Наблюдаемость","События аудита","Исследуйте каждое изменение управления по обезличенным и долговечным свидетельствам.","Экспорт JSONL","Экспорт CSV","Обновить","Фильтры","Ограничьте долговечный поток событий каноническими полями аудита.","Действие","Результат","Все","Тип субъекта","Тип цели","ID запроса","Отпечаток субъекта","Отпечаток цели","Произошло после","Произошло до","Событий на странице","Применить фильтры","Очистить","Запоминаются только фильтры категорий и размер страницы. Корреляционные идентификаторы и временные границы сохраняются лишь в сеансе.","Поток событий","Назад","Страница {page}","Далее","Политика хранения","События удаляются при превышении ограничения по возрасту или количеству.","Дни хранения","Максимум событий","Сохранить политику","Сведения о событии","Закрыть","Время события","ID события","Коды изменений","Копировать ID запроса","Фильтр по ID запроса","Неизвестно","Нет событий аудита, соответствующих этим фильтрам.","Загрузка событий аудита…","Не удалось загрузить события аудита.","Недопустимые фильтры или временной диапазон.","ID запроса скопирован.","Не удалось скопировать ID запроса.","Подготовка ограниченного экспорта…","Экспорт аудита загружен.","Не удалось завершить экспорт аудита.","Сохранить {days} дней и {maxEvents} событий? События за пределами любого лимита могут быть удалены немедленно.","Политика сохранена. Удалено событий: {count}.","Не удалось обновить политику хранения."],
    th: ["ความสามารถในการสังเกตการณ์","เหตุการณ์ตรวจสอบ","ตรวจสอบทุกการเปลี่ยนแปลงการจัดการด้วยหลักฐานที่ปกปิดข้อมูลและคงทน","ส่งออก JSONL","ส่งออก CSV","รีเฟรช","ตัวกรอง","จำกัดสตรีมเหตุการณ์ถาวรด้วยฟิลด์ตรวจสอบมาตรฐาน","การดำเนินการ","ผลลัพธ์","ทั้งหมด","ประเภทผู้ดำเนินการ","ประเภทเป้าหมาย","รหัสคำขอ","ลายนิ้วมือผู้ดำเนินการ","ลายนิ้วมือเป้าหมาย","เกิดหลัง","เกิดก่อน","เหตุการณ์ต่อหน้า","ใช้ตัวกรอง","ล้าง","ระบบจะจำเฉพาะตัวกรองหมวดหมู่และขนาดหน้า ตัวระบุความสัมพันธ์และช่วงเวลาจะอยู่เฉพาะในเซสชัน","สตรีมเหตุการณ์","ก่อนหน้า","หน้า {page}","ถัดไป","นโยบายการเก็บรักษา","เหตุการณ์จะถูกล้างเมื่อเกินขีดจำกัดอายุหรือจำนวน","จำนวนวันที่เก็บ","จำนวนเหตุการณ์สูงสุด","บันทึกการเก็บรักษา","รายละเอียดเหตุการณ์","ปิด","เวลาเกิด","รหัสเหตุการณ์","รหัสการเปลี่ยนแปลง","คัดลอกรหัสคำขอ","กรองตามรหัสคำขอ","ไม่ทราบ","ไม่มีเหตุการณ์ตรวจสอบที่ตรงกับตัวกรองเหล่านี้","กำลังโหลดเหตุการณ์ตรวจสอบ…","ไม่สามารถโหลดเหตุการณ์ตรวจสอบได้","ค่าตัวกรองหรือช่วงเวลาไม่ถูกต้อง","คัดลอกรหัสคำขอแล้ว","ไม่สามารถคัดลอกรหัสคำขอได้","กำลังเตรียมการส่งออกแบบจำกัด…","ดาวน์โหลดข้อมูลตรวจสอบแล้ว","ไม่สามารถส่งออกข้อมูลตรวจสอบได้","บันทึก {days} วันและ {maxEvents} เหตุการณ์หรือไม่ เหตุการณ์ที่เกินขีดจำกัดใดขีดจำกัดหนึ่งอาจถูกลบทันที","บันทึกการเก็บรักษาแล้ว ลบ {count} เหตุการณ์","ไม่สามารถอัปเดตนโยบายการเก็บรักษาได้"],
    tr: ["Gözlemlenebilirlik","Denetim olayları","Her yönetim değişikliğini gizlenmiş ve kalıcı kanıtlarla araştırın.","JSONL dışa aktar","CSV dışa aktar","Yenile","Filtreler","Kalıcı olay akışını standart denetim alanlarıyla daraltın.","Eylem","Sonuç","Tümü","Aktör türü","Hedef türü","İstek kimliği","Aktör parmak izi","Hedef parmak izi","Şundan sonra oluştu","Şundan önce oluştu","Sayfa başına olay","Filtreleri uygula","Temizle","Yalnızca kategori filtreleri ve sayfa boyutu hatırlanır. İlişkilendirme kimlikleri ve zaman sınırları yalnızca oturumda kalır.","Olay akışı","Önceki","Sayfa {page}","Sonraki","Saklama politikası","Yaş veya sayı sınırı aşıldığında olaylar temizlenir.","Saklama günü","En fazla olay","Saklamayı kaydet","Olay ayrıntıları","Kapat","Oluşma zamanı","Olay kimliği","Değişiklik kodları","İstek kimliğini kopyala","İstek kimliğine göre filtrele","Bilinmiyor","Bu filtrelerle eşleşen denetim olayı yok.","Denetim olayları yükleniyor…","Denetim olayları yüklenemedi.","Filtre değerleri veya zaman aralığı geçersiz.","İstek kimliği kopyalandı.","İstek kimliği kopyalanamadı.","Sınırlı dışa aktarım hazırlanıyor…","Denetim dışa aktarımı indirildi.","Denetim dışa aktarımı tamamlanamadı.","{days} gün ve {maxEvents} olay kaydedilsin mi? Herhangi bir sınırın dışındaki olaylar hemen kaldırılabilir.","Saklama kaydedildi. {count} olay kaldırıldı.","Saklama politikası güncellenemedi."],
    vi: ["Khả năng quan sát","Sự kiện kiểm toán","Điều tra mọi thay đổi quản trị bằng bằng chứng đã che dữ liệu nhạy cảm và được lưu bền vững.","Xuất JSONL","Xuất CSV","Làm mới","Bộ lọc","Thu hẹp luồng sự kiện bền vững theo các trường kiểm toán chuẩn.","Thao tác","Kết quả","Tất cả","Loại tác nhân","Loại đối tượng","ID yêu cầu","Dấu vân tay tác nhân","Dấu vân tay đối tượng","Xảy ra sau","Xảy ra trước","Sự kiện mỗi trang","Áp dụng bộ lọc","Xóa","Chỉ bộ lọc phân loại và kích thước trang được ghi nhớ. ID tương quan và mốc thời gian chỉ tồn tại trong phiên.","Luồng sự kiện","Trước","Trang {page}","Tiếp","Chính sách lưu giữ","Sự kiện được dọn khi vượt quá giới hạn thời gian hoặc số lượng.","Số ngày lưu giữ","Số sự kiện tối đa","Lưu chính sách","Chi tiết sự kiện","Đóng","Thời điểm xảy ra","ID sự kiện","Mã thay đổi","Sao chép ID yêu cầu","Lọc theo ID yêu cầu","Không xác định","Không có sự kiện kiểm toán phù hợp với các bộ lọc này.","Đang tải sự kiện kiểm toán…","Không thể tải sự kiện kiểm toán.","Giá trị bộ lọc hoặc khoảng thời gian không hợp lệ.","Đã sao chép ID yêu cầu.","Không thể sao chép ID yêu cầu.","Đang chuẩn bị bản xuất có giới hạn…","Đã tải bản xuất kiểm toán.","Không thể hoàn tất xuất dữ liệu kiểm toán.","Lưu {days} ngày và {maxEvents} sự kiện? Sự kiện vượt một trong hai giới hạn có thể bị xóa ngay lập tức.","Đã lưu chính sách. Đã xóa {count} sự kiện.","Không thể cập nhật chính sách lưu giữ."],
};

const AUDIT_LOCALE_TRANSLATIONS = Object.fromEntries(
    Object.entries(AUDIT_LOCALE_VALUES).map(([locale, messages]) => [
        locale,
        Object.fromEntries(AUDIT_KEYS.map((key, index) => [key, messages[index]]))
    ])
);

for (const [locale, messages] of Object.entries(AUDIT_LOCALE_TRANSLATIONS)) {
    Object.assign(PAGE_LOCALE_TRANSLATIONS[locale], messages);
}
