// Curated operator copy for the Identity and Session Governance console.
// Role, authentication, source, readiness, and ingress codes remain exact protocol values.

const IDENTITY_KEYS = [
    'identity.absolute_expires_at',
    'identity.advance_oidc',
    'identity.authentication',
    'identity.authorization_epoch',
    'identity.authorized',
    'identity.binding_revision',
    'identity.client_credential',
    'identity.configuration_revision',
    'identity.confirm',
    'identity.confirm_advance',
    'identity.confirm_change_title',
    'identity.confirm_disable',
    'identity.confirm_enable',
    'identity.confirm_owner_create',
    'identity.confirm_revoke',
    'identity.confirm_revoke_current',
    'identity.confirm_role',
    'identity.create',
    'identity.create_description',
    'identity.create_identity',
    'identity.create_owner',
    'identity.current',
    'identity.current_principal',
    'identity.current_principal_description',
    'identity.current_session_revoked',
    'identity.description',
    'identity.disable',
    'identity.enable',
    'identity.governance',
    'identity.identities',
    'identity.identities_description',
    'identity.identity_id',
    'identity.identity_revision',
    'identity.idle_expires_at',
    'identity.ingress_policy',
    'identity.invalid',
    'identity.issued_at',
    'identity.issuer',
    'identity.label',
    'identity.last_seen_at',
    'identity.load_failed',
    'identity.local',
    'identity.local_owner',
    'identity.local_owner_identity',
    'identity.no',
    'identity.no_change',
    'identity.no_identities',
    'identity.no_sessions',
    'identity.not_authorized',
    'identity.not_configured',
    'identity.not_found',
    'identity.not_ready',
    'identity.oidc_readiness',
    'identity.oidc_readiness_description',
    'identity.page',
    'identity.password',
    'identity.permission_denied',
    'identity.permissions',
    'identity.policy_advanced',
    'identity.policy_advanced_incomplete',
    'identity.principal_type',
    'identity.ready',
    'identity.recovery',
    'identity.recovery_description',
    'identity.redirect_uri',
    'identity.refresh',
    'identity.refreshed',
    'identity.request_failed',
    'identity.revoke',
    'identity.revoked',
    'identity.role',
    'identity.role_mappings',
    'identity.role_source',
    'identity.save_role',
    'identity.saved',
    'identity.scopes',
    'identity.sessions',
    'identity.sessions_description',
    'identity.stale_revision',
    'identity.subject',
    'identity.title',
    'identity.unavailable',
    'identity.updated_at',
    'identity.yes',
];

const IDENTITY_LOCALE_VALUES = {
    en: ["Absolute expiry","Invalidate OIDC sessions","Authentication","Authorization epoch","Authorized","Binding revision","Client credential configured","Configuration revision","Confirm","This advances the authorization epoch and invalidates every OIDC session. Continue?","Confirm governance change","Disable identity {id}? Its active sessions will no longer authorize requests.","Enable identity {id}?","Create an owner binding? Owners receive full management authority.","Revoke the session for {id}?","Revoke your current session? You will be signed out immediately.","Change {id} to role {role}? Existing sessions will be invalidated.","Create","Bind one exact OIDC issuer and subject to a direct management role.","Create identity","Create owner","Current","Current principal","Authority used for this console request.","The current session was revoked. Sign in again to continue.","Review effective authority, direct OIDC identities, active management sessions, and recovery readiness.","Disable","Enable","Governance","Direct identities","Exact issuer and subject bindings with durable role revisions.","Identity ID","Identity revision","Idle expiry","Ingress policy","Invalid","Issued at","Issuer","Identity","Last seen","Identity state could not be loaded.","Local","Local owner","Local owner identity","No","No change is required.","No direct identities are available.","No active management sessions are available.","Your principal is not authorized for this resource.","Not configured","The requested resource was not found.","Not ready","OIDC readiness","Safe configuration projection and authorization epoch.","Page {page}","Password","Permission denied.","Effective permissions","OIDC policy advanced; {count} sessions were revoked.","The durable policy advanced, but eager session cleanup was incomplete.","Principal type","Ready","Recovery readiness","Emergency local-owner access and effective ingress boundary.","Redirect URI","Refresh identity state","Identity state refreshed.","The identity operation could not be completed.","Revoke","Revoked","Role","Role mappings","Role source","Save role","Changes saved.","Scopes","Active sessions","Bounded management sessions represented by non-authenticating references.","The resource changed elsewhere. Review the current values and submit again.","Subject","Identity and sessions","Unavailable","Updated at","Yes"],
    'zh-CN': ["绝对到期时间","使 OIDC 会话失效","身份验证","授权纪元","已授权","绑定修订版","已配置客户端凭据","配置修订版","确认","这将推进授权纪元并使所有 OIDC 会话失效。是否继续？","确认治理更改","停用身份 {id}？其活动会话将无法再授权请求。","启用身份 {id}？","创建所有者绑定？所有者拥有完整管理权限。","撤销 {id} 的会话？","撤销当前会话？您将立即退出登录。","将 {id} 更改为角色 {role}？现有会话将失效。","创建","将一个精确的 OIDC 颁发者和主体绑定到直接管理角色。","创建身份","创建所有者","当前","当前主体","本次控制台请求使用的权限。","当前会话已撤销。请重新登录以继续。","查看有效权限、直接 OIDC 身份、活动管理会话和恢复就绪状态。","停用","启用","治理","直接身份","具有持久角色修订版的精确颁发者和主体绑定。","身份 ID","身份修订版","空闲到期时间","入口策略","无效","签发时间","颁发者","身份","最近活动","无法加载身份状态。","本地","本地所有者","本地所有者身份","否","无需更改。","没有可用的直接身份。","没有活动的管理会话。","您的主体无权访问此资源。","未配置","未找到请求的资源。","未就绪","OIDC 就绪状态","安全配置投影和授权纪元。","第 {page} 页","密码","权限被拒绝。","有效权限","OIDC 策略已推进；已撤销 {count} 个会话。","持久策略已推进，但即时会话清理未完成。","主体类型","就绪","恢复就绪状态","紧急本地所有者访问和有效入口边界。","重定向 URI","刷新身份状态","身份状态已刷新。","无法完成身份操作。","撤销","已撤销","角色","角色映射","角色来源","保存角色","更改已保存。","范围","活动会话","由不可用于身份验证的引用表示的有界管理会话。","资源已在其他位置更改。请检查当前值后重新提交。","主体","身份和会话","不可用","更新时间","是"],
    'zh-TW': ["絕對到期時間","使 OIDC 工作階段失效","驗證","授權世代","已授權","繫結修訂版","已設定用戶端憑證","設定修訂版","確認","這會推進授權世代並使所有 OIDC 工作階段失效。要繼續嗎？","確認治理變更","停用身分 {id}？其作用中的工作階段將無法再授權要求。","啟用身分 {id}？","建立擁有者繫結？擁有者具備完整管理權限。","撤銷 {id} 的工作階段？","撤銷目前工作階段？您將立即登出。","將 {id} 改為角色 {role}？現有工作階段將失效。","建立","將一個精確的 OIDC 發行者與主體繫結至直接管理角色。","建立身分","建立擁有者","目前","目前主體","此控制台要求所使用的權限。","目前工作階段已撤銷。請重新登入以繼續。","檢視有效權限、直接 OIDC 身分、作用中管理工作階段及復原就緒狀態。","停用","啟用","治理","直接身分","具有持久角色修訂版的精確發行者與主體繫結。","身分 ID","身分修訂版","閒置到期時間","入口政策","無效","簽發時間","發行者","身分","最近活動","無法載入身分狀態。","本機","本機擁有者","本機擁有者身分","否","不需要變更。","沒有可用的直接身分。","沒有作用中的管理工作階段。","您的主體未獲授權存取此資源。","未設定","找不到要求的資源。","未就緒","OIDC 就緒狀態","安全設定投影與授權世代。","第 {page} 頁","密碼","權限遭拒。","有效權限","OIDC 政策已推進；已撤銷 {count} 個工作階段。","持久政策已推進，但即時工作階段清理未完成。","主體類型","就緒","復原就緒狀態","緊急本機擁有者存取與有效入口邊界。","重新導向 URI","重新整理身分狀態","身分狀態已重新整理。","無法完成身分作業。","撤銷","已撤銷","角色","角色對應","角色來源","儲存角色","變更已儲存。","範圍","作用中工作階段","以不可用於驗證的參照表示的有限管理工作階段。","資源已在其他位置變更。請檢查目前值後再次提交。","主體","身分與工作階段","無法使用","更新時間","是"],
    de: ["Absoluter Ablauf","OIDC-Sitzungen ungültig machen","Authentifizierung","Autorisierungsepoche","Autorisiert","Bindungsrevision","Client-Zugangsdaten konfiguriert","Konfigurationsrevision","Bestätigen","Damit wird die Autorisierungsepoche erhöht und jede OIDC-Sitzung ungültig. Fortfahren?","Governance-Änderung bestätigen","Identität {id} deaktivieren? Aktive Sitzungen können dann keine Anfragen mehr autorisieren.","Identität {id} aktivieren?","Eine Eigentümerbindung erstellen? Eigentümer erhalten vollständige Verwaltungsrechte.","Sitzung für {id} widerrufen?","Aktuelle Sitzung widerrufen? Sie werden sofort abgemeldet.","{id} auf Rolle {role} ändern? Bestehende Sitzungen werden ungültig.","Erstellen","Einen exakten OIDC-Aussteller und Betreff an eine direkte Verwaltungsrolle binden.","Identität erstellen","Eigentümer erstellen","Aktuell","Aktueller Principal","Für diese Konsolenanfrage verwendete Berechtigung.","Die aktuelle Sitzung wurde widerrufen. Melden Sie sich erneut an.","Effektive Berechtigungen, direkte OIDC-Identitäten, aktive Verwaltungssitzungen und Wiederherstellungsbereitschaft prüfen.","Deaktivieren","Aktivieren","Governance","Direkte Identitäten","Exakte Aussteller- und Betreffbindungen mit dauerhaften Rollenrevisionen.","Identitäts-ID","Identitätsrevision","Leerlaufablauf","Zugangsrichtlinie","Ungültig","Ausgestellt am","Aussteller","Identität","Zuletzt gesehen","Identitätsstatus konnte nicht geladen werden.","Lokal","Lokaler Eigentümer","Lokale Eigentümeridentität","Nein","Keine Änderung erforderlich.","Keine direkten Identitäten verfügbar.","Keine aktiven Verwaltungssitzungen verfügbar.","Ihr Principal ist für diese Ressource nicht autorisiert.","Nicht konfiguriert","Die angeforderte Ressource wurde nicht gefunden.","Nicht bereit","OIDC-Bereitschaft","Sichere Konfigurationsansicht und Autorisierungsepoche.","Seite {page}","Passwort","Berechtigung verweigert.","Effektive Berechtigungen","OIDC-Richtlinie erhöht; {count} Sitzungen wurden widerrufen.","Die dauerhafte Richtlinie wurde erhöht, aber die sofortige Sitzungsbereinigung blieb unvollständig.","Principal-Typ","Bereit","Wiederherstellungsbereitschaft","Notfallzugang für den lokalen Eigentümer und wirksame Zugangsgrenze.","Weiterleitungs-URI","Identitätsstatus aktualisieren","Identitätsstatus aktualisiert.","Der Identitätsvorgang konnte nicht abgeschlossen werden.","Widerrufen","Widerrufen","Rolle","Rollenzuordnungen","Rollenquelle","Rolle speichern","Änderungen gespeichert.","Bereiche","Aktive Sitzungen","Begrenzte Verwaltungssitzungen mit nicht authentifizierenden Referenzen.","Die Ressource wurde an anderer Stelle geändert. Prüfen Sie die aktuellen Werte und senden Sie erneut.","Betreff","Identitäten und Sitzungen","Nicht verfügbar","Aktualisiert am","Ja"],
    es: ["Caducidad absoluta","Invalidar sesiones OIDC","Autenticación","Época de autorización","Autorizado","Revisión de vinculación","Credencial de cliente configurada","Revisión de configuración","Confirmar","Esto avanza la época de autorización e invalida todas las sesiones OIDC. ¿Continuar?","Confirmar cambio de gobernanza","¿Desactivar la identidad {id}? Sus sesiones activas dejarán de autorizar solicitudes.","¿Activar la identidad {id}?","¿Crear una vinculación de propietario? Los propietarios reciben autoridad administrativa total.","¿Revocar la sesión de {id}?","¿Revocar la sesión actual? Se cerrará de inmediato.","¿Cambiar {id} al rol {role}? Las sesiones existentes se invalidarán.","Crear","Vincula un emisor y sujeto OIDC exactos a un rol administrativo directo.","Crear identidad","Crear propietario","Actual","Principal actual","Autoridad utilizada para esta solicitud de consola.","La sesión actual fue revocada. Inicia sesión de nuevo para continuar.","Revisa la autoridad efectiva, las identidades OIDC directas, las sesiones administrativas activas y la preparación de recuperación.","Desactivar","Activar","Gobernanza","Identidades directas","Vinculaciones exactas de emisor y sujeto con revisiones de rol duraderas.","ID de identidad","Revisión de identidad","Caducidad por inactividad","Política de ingreso","No válido","Emitida el","Emisor","Identidad","Última actividad","No se pudo cargar el estado de identidad.","Local","Propietario local","Identidad de propietario local","No","No se requiere ningún cambio.","No hay identidades directas disponibles.","No hay sesiones administrativas activas.","Tu principal no está autorizado para este recurso.","Sin configurar","No se encontró el recurso solicitado.","No preparado","Preparación de OIDC","Proyección segura de configuración y época de autorización.","Página {page}","Contraseña","Permiso denegado.","Permisos efectivos","Política OIDC avanzada; se revocaron {count} sesiones.","La política duradera avanzó, pero la limpieza inmediata de sesiones quedó incompleta.","Tipo de principal","Preparado","Preparación de recuperación","Acceso de emergencia del propietario local y límite de ingreso efectivo.","URI de redirección","Actualizar estado de identidad","Estado de identidad actualizado.","No se pudo completar la operación de identidad.","Revocar","Revocada","Rol","Mapeos de roles","Origen del rol","Guardar rol","Cambios guardados.","Ámbitos","Sesiones activas","Sesiones administrativas acotadas representadas por referencias que no autentican.","El recurso cambió en otro lugar. Revisa los valores actuales y vuelve a enviar.","Sujeto","Identidad y sesiones","No disponible","Actualizada el","Sí"],
    fr: ["Expiration absolue","Invalider les sessions OIDC","Authentification","Époque d’autorisation","Autorisé","Révision de liaison","Identifiant client configuré","Révision de configuration","Confirmer","Cette action avance l’époque d’autorisation et invalide toutes les sessions OIDC. Continuer ?","Confirmer la modification de gouvernance","Désactiver l’identité {id} ? Ses sessions actives ne pourront plus autoriser de requêtes.","Activer l’identité {id} ?","Créer une liaison propriétaire ? Les propriétaires disposent de tous les droits d’administration.","Révoquer la session de {id} ?","Révoquer votre session actuelle ? Vous serez immédiatement déconnecté.","Attribuer le rôle {role} à {id} ? Les sessions existantes seront invalidées.","Créer","Liez un émetteur et un sujet OIDC exacts à un rôle d’administration direct.","Créer une identité","Créer un propriétaire","Actuelle","Principal actuel","Autorité utilisée pour cette requête de console.","La session actuelle a été révoquée. Reconnectez-vous pour continuer.","Examinez l’autorité effective, les identités OIDC directes, les sessions d’administration actives et l’état de récupération.","Désactiver","Activer","Gouvernance","Identités directes","Liaisons exactes d’émetteur et de sujet avec révisions de rôle durables.","ID d’identité","Révision d’identité","Expiration d’inactivité","Politique d’accès","Invalide","Émise le","Émetteur","Identité","Dernière activité","Impossible de charger l’état des identités.","Locale","Propriétaire local","Identité du propriétaire local","Non","Aucune modification nécessaire.","Aucune identité directe disponible.","Aucune session d’administration active.","Votre principal n’est pas autorisé pour cette ressource.","Non configuré","La ressource demandée est introuvable.","Non prêt","État OIDC","Projection sûre de la configuration et époque d’autorisation.","Page {page}","Mot de passe","Autorisation refusée.","Autorisations effectives","Politique OIDC avancée ; {count} sessions révoquées.","La politique durable a avancé, mais le nettoyage immédiat des sessions est incomplet.","Type de principal","Prêt","État de récupération","Accès d’urgence du propriétaire local et frontière d’accès effective.","URI de redirection","Actualiser l’état des identités","État des identités actualisé.","Impossible de terminer l’opération d’identité.","Révoquer","Révoquée","Rôle","Mappages de rôles","Source du rôle","Enregistrer le rôle","Modifications enregistrées.","Portées","Sessions actives","Sessions d’administration bornées représentées par des références non authentifiantes.","La ressource a été modifiée ailleurs. Vérifiez les valeurs actuelles et renvoyez.","Sujet","Identités et sessions","Indisponible","Mise à jour le","Oui"],
    id: ["Kedaluwarsa absolut","Batalkan sesi OIDC","Autentikasi","Epoch otorisasi","Diotorisasi","Revisi pengikatan","Kredensial klien dikonfigurasi","Revisi konfigurasi","Konfirmasi","Tindakan ini memajukan epoch otorisasi dan membatalkan semua sesi OIDC. Lanjutkan?","Konfirmasi perubahan tata kelola","Nonaktifkan identitas {id}? Sesi aktifnya tidak lagi dapat mengotorisasi permintaan.","Aktifkan identitas {id}?","Buat pengikatan pemilik? Pemilik mendapat kewenangan pengelolaan penuh.","Cabut sesi untuk {id}?","Cabut sesi saat ini? Anda akan segera keluar.","Ubah {id} ke peran {role}? Sesi yang ada akan dibatalkan.","Buat","Ikat satu penerbit dan subjek OIDC yang tepat ke peran pengelolaan langsung.","Buat identitas","Buat pemilik","Saat ini","Prinsipal saat ini","Kewenangan yang dipakai untuk permintaan konsol ini.","Sesi saat ini telah dicabut. Masuk lagi untuk melanjutkan.","Tinjau kewenangan efektif, identitas OIDC langsung, sesi pengelolaan aktif, dan kesiapan pemulihan.","Nonaktifkan","Aktifkan","Tata kelola","Identitas langsung","Pengikatan penerbit dan subjek yang tepat dengan revisi peran yang tahan lama.","ID identitas","Revisi identitas","Kedaluwarsa diam","Kebijakan akses masuk","Tidak valid","Diterbitkan","Penerbit","Identitas","Terakhir terlihat","Status identitas tidak dapat dimuat.","Lokal","Pemilik lokal","Identitas pemilik lokal","Tidak","Tidak diperlukan perubahan.","Tidak ada identitas langsung.","Tidak ada sesi pengelolaan aktif.","Prinsipal Anda tidak berwenang untuk sumber daya ini.","Belum dikonfigurasi","Sumber daya yang diminta tidak ditemukan.","Belum siap","Kesiapan OIDC","Proyeksi konfigurasi aman dan epoch otorisasi.","Halaman {page}","Kata sandi","Izin ditolak.","Izin efektif","Kebijakan OIDC dimajukan; {count} sesi dicabut.","Kebijakan tahan lama dimajukan, tetapi pembersihan sesi segera belum lengkap.","Jenis prinsipal","Siap","Kesiapan pemulihan","Akses darurat pemilik lokal dan batas akses masuk efektif.","URI pengalihan","Muat ulang status identitas","Status identitas dimuat ulang.","Operasi identitas tidak dapat diselesaikan.","Cabut","Dicabut","Peran","Pemetaan peran","Sumber peran","Simpan peran","Perubahan disimpan.","Cakupan","Sesi aktif","Sesi pengelolaan terbatas yang diwakili referensi nonautentikasi.","Sumber daya diubah di tempat lain. Tinjau nilai saat ini lalu kirim lagi.","Subjek","Identitas dan sesi","Tidak tersedia","Diperbarui","Ya"],
    it: ["Scadenza assoluta","Invalida sessioni OIDC","Autenticazione","Epoca di autorizzazione","Autorizzato","Revisione associazione","Credenziale client configurata","Revisione configurazione","Conferma","Questa azione avanza l’epoca di autorizzazione e invalida tutte le sessioni OIDC. Continuare?","Conferma modifica di governance","Disabilitare l’identità {id}? Le sessioni attive non potranno più autorizzare richieste.","Abilitare l’identità {id}?","Creare un’associazione proprietario? I proprietari ricevono piena autorità amministrativa.","Revocare la sessione di {id}?","Revocare la sessione corrente? Verrai disconnesso immediatamente.","Cambiare {id} al ruolo {role}? Le sessioni esistenti saranno invalidate.","Crea","Associa un emittente e un soggetto OIDC esatti a un ruolo amministrativo diretto.","Crea identità","Crea proprietario","Corrente","Principal corrente","Autorità usata per questa richiesta della console.","La sessione corrente è stata revocata. Accedi di nuovo per continuare.","Esamina autorità effettiva, identità OIDC dirette, sessioni amministrative attive e prontezza del recupero.","Disabilita","Abilita","Governance","Identità dirette","Associazioni esatte di emittente e soggetto con revisioni ruolo persistenti.","ID identità","Revisione identità","Scadenza inattività","Criterio di ingresso","Non valido","Emessa il","Emittente","Identità","Ultima attività","Impossibile caricare lo stato delle identità.","Locale","Proprietario locale","Identità del proprietario locale","No","Non è necessaria alcuna modifica.","Nessuna identità diretta disponibile.","Nessuna sessione amministrativa attiva.","Il principal non è autorizzato per questa risorsa.","Non configurato","La risorsa richiesta non è stata trovata.","Non pronto","Prontezza OIDC","Proiezione sicura della configurazione ed epoca di autorizzazione.","Pagina {page}","Password","Autorizzazione negata.","Autorizzazioni effettive","Criterio OIDC avanzato; {count} sessioni revocate.","Il criterio persistente è avanzato, ma la pulizia immediata delle sessioni è incompleta.","Tipo principal","Pronto","Prontezza recupero","Accesso di emergenza del proprietario locale e confine di ingresso effettivo.","URI di reindirizzamento","Aggiorna stato identità","Stato identità aggiornato.","Impossibile completare l’operazione di identità.","Revoca","Revocata","Ruolo","Mappature ruoli","Origine ruolo","Salva ruolo","Modifiche salvate.","Ambiti","Sessioni attive","Sessioni amministrative limitate rappresentate da riferimenti non autenticanti.","La risorsa è cambiata altrove. Controlla i valori correnti e invia di nuovo.","Soggetto","Identità e sessioni","Non disponibile","Aggiornata il","Sì"],
    ja: ["絶対有効期限","OIDC セッションを無効化","認証","認可エポック","認可済み","バインド改訂","クライアント認証情報設定済み","構成改訂","確認","認可エポックを進め、すべての OIDC セッションを無効にします。続行しますか？","ガバナンス変更の確認","ID {id} を無効にしますか？アクティブなセッションは要求を認可できなくなります。","ID {id} を有効にしますか？","所有者バインドを作成しますか？所有者には完全な管理権限が付与されます。","{id} のセッションを取り消しますか？","現在のセッションを取り消しますか？直ちにサインアウトします。","{id} のロールを {role} に変更しますか？既存のセッションは無効になります。","作成","正確な OIDC 発行者とサブジェクトを直接管理ロールにバインドします。","ID を作成","所有者を作成","現在","現在のプリンシパル","このコンソール要求で使用される権限です。","現在のセッションは取り消されました。再度サインインしてください。","有効な権限、直接 OIDC ID、アクティブな管理セッション、復旧準備状況を確認します。","無効化","有効化","ガバナンス","直接 ID","永続的なロール改訂を持つ正確な発行者とサブジェクトのバインドです。","ID 識別子","ID 改訂","アイドル有効期限","受信ポリシー","無効","発行日時","発行者","ID","最終確認","ID 状態を読み込めませんでした。","ローカル","ローカル所有者","ローカル所有者 ID","いいえ","変更は不要です。","直接 ID はありません。","アクティブな管理セッションはありません。","このリソースに対する権限がありません。","未構成","要求されたリソースが見つかりません。","未準備","OIDC 準備状況","安全な構成表示と認可エポックです。","ページ {page}","パスワード","権限が拒否されました。","有効な権限","OIDC ポリシーを進め、{count} 件のセッションを取り消しました。","永続ポリシーは進みましたが、即時セッション削除は完了していません。","プリンシパル種別","準備完了","復旧準備状況","緊急ローカル所有者アクセスと有効な受信境界です。","リダイレクト URI","ID 状態を更新","ID 状態を更新しました。","ID 操作を完了できませんでした。","取り消す","取り消し済み","ロール","ロールマッピング","ロールのソース","ロールを保存","変更を保存しました。","スコープ","アクティブなセッション","認証に使用できない参照で表される制限付き管理セッションです。","リソースが別の場所で変更されました。現在の値を確認して再送信してください。","サブジェクト","ID とセッション","利用不可","更新日時","はい"],
    ko: ["절대 만료","OIDC 세션 무효화","인증","권한 부여 에포크","권한 있음","바인딩 개정","클라이언트 자격 증명 구성됨","구성 개정","확인","권한 부여 에포크를 진행하고 모든 OIDC 세션을 무효화합니다. 계속할까요?","거버넌스 변경 확인","ID {id}을(를) 비활성화할까요? 활성 세션은 더 이상 요청을 승인할 수 없습니다.","ID {id}을(를) 활성화할까요?","소유자 바인딩을 만들까요? 소유자는 전체 관리 권한을 받습니다.","{id}의 세션을 해지할까요?","현재 세션을 해지할까요? 즉시 로그아웃됩니다.","{id}의 역할을 {role}(으)로 변경할까요? 기존 세션이 무효화됩니다.","만들기","정확한 OIDC 발급자와 주체를 직접 관리 역할에 바인딩합니다.","ID 만들기","소유자 만들기","현재","현재 주체","이 콘솔 요청에 사용된 권한입니다.","현재 세션이 해지되었습니다. 계속하려면 다시 로그인하세요.","유효 권한, 직접 OIDC ID, 활성 관리 세션 및 복구 준비 상태를 검토합니다.","비활성화","활성화","거버넌스","직접 ID","영구 역할 개정이 있는 정확한 발급자 및 주체 바인딩입니다.","ID 식별자","ID 개정","유휴 만료","수신 정책","유효하지 않음","발급 시각","발급자","ID","마지막 활동","ID 상태를 불러올 수 없습니다.","로컬","로컬 소유자","로컬 소유자 ID","아니요","변경할 필요가 없습니다.","사용 가능한 직접 ID가 없습니다.","활성 관리 세션이 없습니다.","이 리소스에 대한 주체 권한이 없습니다.","구성되지 않음","요청한 리소스를 찾을 수 없습니다.","준비되지 않음","OIDC 준비 상태","안전한 구성 보기와 권한 부여 에포크입니다.","페이지 {page}","비밀번호","권한이 거부되었습니다.","유효 권한","OIDC 정책을 진행하고 {count}개 세션을 해지했습니다.","영구 정책은 진행되었지만 즉시 세션 정리가 완료되지 않았습니다.","주체 유형","준비됨","복구 준비 상태","긴급 로컬 소유자 액세스와 유효 수신 경계입니다.","리디렉션 URI","ID 상태 새로 고침","ID 상태를 새로 고쳤습니다.","ID 작업을 완료할 수 없습니다.","해지","해지됨","역할","역할 매핑","역할 출처","역할 저장","변경 사항을 저장했습니다.","범위","활성 세션","인증할 수 없는 참조로 표시되는 제한된 관리 세션입니다.","리소스가 다른 곳에서 변경되었습니다. 현재 값을 검토하고 다시 제출하세요.","주체","ID 및 세션","사용할 수 없음","업데이트 시각","예"],
    pt: ["Expiração absoluta","Invalidar sessões OIDC","Autenticação","Época de autorização","Autorizado","Revisão do vínculo","Credencial do cliente configurada","Revisão da configuração","Confirmar","Isso avança a época de autorização e invalida todas as sessões OIDC. Continuar?","Confirmar alteração de governança","Desativar a identidade {id}? As sessões ativas não poderão mais autorizar solicitações.","Ativar a identidade {id}?","Criar um vínculo de proprietário? Proprietários recebem autoridade administrativa total.","Revogar a sessão de {id}?","Revogar a sessão atual? Você será desconectado imediatamente.","Alterar {id} para a função {role}? As sessões existentes serão invalidadas.","Criar","Vincule um emissor e sujeito OIDC exatos a uma função administrativa direta.","Criar identidade","Criar proprietário","Atual","Principal atual","Autoridade usada para esta solicitação do console.","A sessão atual foi revogada. Entre novamente para continuar.","Revise a autoridade efetiva, identidades OIDC diretas, sessões administrativas ativas e prontidão de recuperação.","Desativar","Ativar","Governança","Identidades diretas","Vínculos exatos de emissor e sujeito com revisões de função duráveis.","ID da identidade","Revisão da identidade","Expiração por inatividade","Política de entrada","Inválido","Emitida em","Emissor","Identidade","Última atividade","Não foi possível carregar o estado das identidades.","Local","Proprietário local","Identidade do proprietário local","Não","Nenhuma alteração é necessária.","Nenhuma identidade direta disponível.","Nenhuma sessão administrativa ativa.","Seu principal não está autorizado para este recurso.","Não configurado","O recurso solicitado não foi encontrado.","Não pronto","Prontidão do OIDC","Projeção segura da configuração e época de autorização.","Página {page}","Senha","Permissão negada.","Permissões efetivas","Política OIDC avançada; {count} sessões foram revogadas.","A política durável avançou, mas a limpeza imediata de sessões ficou incompleta.","Tipo de principal","Pronto","Prontidão de recuperação","Acesso de emergência do proprietário local e limite de entrada efetivo.","URI de redirecionamento","Atualizar estado das identidades","Estado das identidades atualizado.","Não foi possível concluir a operação de identidade.","Revogar","Revogada","Função","Mapeamentos de função","Origem da função","Salvar função","Alterações salvas.","Escopos","Sessões ativas","Sessões administrativas limitadas representadas por referências que não autenticam.","O recurso mudou em outro lugar. Revise os valores atuais e envie novamente.","Sujeito","Identidades e sessões","Indisponível","Atualizada em","Sim"],
    ru: ["Абсолютное истечение","Аннулировать сеансы OIDC","Аутентификация","Эпоха авторизации","Авторизован","Ревизия привязки","Учётные данные клиента настроены","Ревизия конфигурации","Подтвердить","Это повысит эпоху авторизации и аннулирует все сеансы OIDC. Продолжить?","Подтвердить изменение управления","Отключить идентичность {id}? Активные сеансы больше не смогут авторизовать запросы.","Включить идентичность {id}?","Создать привязку владельца? Владельцы получают полные права управления.","Отозвать сеанс для {id}?","Отозвать текущий сеанс? Вы немедленно выйдете из системы.","Изменить роль {id} на {role}? Существующие сеансы будут аннулированы.","Создать","Привяжите точные издателя и субъект OIDC к прямой роли управления.","Создать идентичность","Создать владельца","Текущий","Текущий субъект","Полномочия, используемые для этого запроса консоли.","Текущий сеанс отозван. Войдите снова, чтобы продолжить.","Проверьте эффективные полномочия, прямые идентичности OIDC, активные сеансы управления и готовность восстановления.","Отключить","Включить","Управление","Прямые идентичности","Точные привязки издателя и субъекта с долговечными ревизиями роли.","ID идентичности","Ревизия идентичности","Истечение простоя","Политика входа","Недействительно","Выдан","Издатель","Идентичность","Последняя активность","Не удалось загрузить состояние идентичностей.","Локальный","Локальный владелец","Идентичность локального владельца","Нет","Изменение не требуется.","Прямые идентичности отсутствуют.","Активные сеансы управления отсутствуют.","Ваш субъект не авторизован для этого ресурса.","Не настроено","Запрошенный ресурс не найден.","Не готово","Готовность OIDC","Безопасная проекция конфигурации и эпоха авторизации.","Страница {page}","Пароль","Доступ запрещён.","Эффективные разрешения","Политика OIDC продвинута; отозвано сеансов: {count}.","Долговечная политика продвинута, но немедленная очистка сеансов не завершена.","Тип субъекта","Готово","Готовность восстановления","Аварийный доступ локального владельца и эффективная граница входа.","URI перенаправления","Обновить состояние идентичностей","Состояние идентичностей обновлено.","Не удалось завершить операцию с идентичностью.","Отозвать","Отозвано","Роль","Сопоставления ролей","Источник роли","Сохранить роль","Изменения сохранены.","Области","Активные сеансы","Ограниченные сеансы управления, представленные неаутентифицирующими ссылками.","Ресурс изменён в другом месте. Проверьте текущие значения и отправьте снова.","Субъект","Идентичности и сеансы","Недоступно","Обновлено","Да"],
    th: ["หมดอายุแบบสัมบูรณ์","ทำให้เซสชัน OIDC ใช้ไม่ได้","การยืนยันตัวตน","ยุคการอนุญาต","ได้รับอนุญาต","รุ่นการผูก","กำหนดค่าข้อมูลรับรองไคลเอนต์แล้ว","รุ่นการกำหนดค่า","ยืนยัน","การดำเนินการนี้จะเลื่อนยุคการอนุญาตและทำให้เซสชัน OIDC ทั้งหมดใช้ไม่ได้ ดำเนินการต่อหรือไม่","ยืนยันการเปลี่ยนแปลงการกำกับดูแล","ปิดใช้งานข้อมูลประจำตัว {id} หรือไม่ เซสชันที่ใช้งานอยู่จะไม่สามารถอนุญาตคำขอได้อีก","เปิดใช้งานข้อมูลประจำตัว {id} หรือไม่","สร้างการผูกเจ้าของหรือไม่ เจ้าของจะได้รับสิทธิ์การจัดการทั้งหมด","เพิกถอนเซสชันของ {id} หรือไม่","เพิกถอนเซสชันปัจจุบันหรือไม่ คุณจะออกจากระบบทันที","เปลี่ยน {id} เป็นบทบาท {role} หรือไม่ เซสชันเดิมจะใช้ไม่ได้","สร้าง","ผูกผู้ออกและหัวเรื่อง OIDC ที่ตรงกันกับบทบาทการจัดการโดยตรง","สร้างข้อมูลประจำตัว","สร้างเจ้าของ","ปัจจุบัน","ผู้ใช้งานปัจจุบัน","สิทธิ์ที่ใช้สำหรับคำขอคอนโซลนี้","เซสชันปัจจุบันถูกเพิกถอน โปรดเข้าสู่ระบบอีกครั้ง","ตรวจสอบสิทธิ์ที่มีผล ข้อมูลประจำตัว OIDC โดยตรง เซสชันการจัดการที่ใช้งาน และความพร้อมกู้คืน","ปิดใช้งาน","เปิดใช้งาน","การกำกับดูแล","ข้อมูลประจำตัวโดยตรง","การผูกผู้ออกและหัวเรื่องที่ตรงกันพร้อมรุ่นบทบาทแบบคงทน","รหัสข้อมูลประจำตัว","รุ่นข้อมูลประจำตัว","หมดอายุเมื่อไม่ได้ใช้งาน","นโยบายทางเข้า","ไม่ถูกต้อง","ออกเมื่อ","ผู้ออก","ข้อมูลประจำตัว","พบล่าสุด","ไม่สามารถโหลดสถานะข้อมูลประจำตัวได้","ภายในเครื่อง","เจ้าของภายในเครื่อง","ข้อมูลประจำตัวเจ้าของภายในเครื่อง","ไม่","ไม่จำเป็นต้องเปลี่ยนแปลง","ไม่มีข้อมูลประจำตัวโดยตรง","ไม่มีเซสชันการจัดการที่ใช้งาน","ผู้ใช้งานของคุณไม่มีสิทธิ์สำหรับทรัพยากรนี้","ยังไม่ได้กำหนดค่า","ไม่พบทรัพยากรที่ร้องขอ","ไม่พร้อม","ความพร้อม OIDC","มุมมองการกำหนดค่าที่ปลอดภัยและยุคการอนุญาต","หน้า {page}","รหัสผ่าน","ปฏิเสธสิทธิ์","สิทธิ์ที่มีผล","เลื่อนนโยบาย OIDC แล้ว เพิกถอน {count} เซสชัน","นโยบายถาวรถูกเลื่อนแล้ว แต่การล้างเซสชันทันทียังไม่สมบูรณ์","ประเภทผู้ใช้งาน","พร้อม","ความพร้อมกู้คืน","การเข้าถึงฉุกเฉินของเจ้าของภายในเครื่องและขอบเขตทางเข้าที่มีผล","URI เปลี่ยนเส้นทาง","รีเฟรชสถานะข้อมูลประจำตัว","รีเฟรชสถานะข้อมูลประจำตัวแล้ว","ไม่สามารถดำเนินการข้อมูลประจำตัวให้เสร็จได้","เพิกถอน","เพิกถอนแล้ว","บทบาท","การแมปบทบาท","แหล่งที่มาของบทบาท","บันทึกบทบาท","บันทึกการเปลี่ยนแปลงแล้ว","ขอบเขต","เซสชันที่ใช้งาน","เซสชันการจัดการแบบจำกัดที่แสดงด้วยข้อมูลอ้างอิงซึ่งใช้ยืนยันตัวตนไม่ได้","ทรัพยากรถูกเปลี่ยนจากที่อื่น ตรวจสอบค่าปัจจุบันแล้วส่งอีกครั้ง","หัวเรื่อง","ข้อมูลประจำตัวและเซสชัน","ไม่พร้อมใช้งาน","อัปเดตเมื่อ","ใช่"],
    tr: ["Kesin sona erme","OIDC oturumlarını geçersiz kıl","Kimlik doğrulama","Yetkilendirme dönemi","Yetkili","Bağlama revizyonu","İstemci kimlik bilgisi yapılandırıldı","Yapılandırma revizyonu","Onayla","Bu işlem yetkilendirme dönemini ilerletir ve tüm OIDC oturumlarını geçersiz kılar. Devam edilsin mi?","Yönetişim değişikliğini onayla","{id} kimliği devre dışı bırakılsın mı? Etkin oturumları artık istekleri yetkilendiremez.","{id} kimliği etkinleştirilsin mi?","Sahip bağlaması oluşturulsun mu? Sahipler tam yönetim yetkisi alır.","{id} oturumu iptal edilsin mi?","Geçerli oturum iptal edilsin mi? Hemen çıkış yapacaksınız.","{id}, {role} rolüne değiştirilsin mi? Mevcut oturumlar geçersiz kılınır.","Oluştur","Tam bir OIDC yayımcısını ve öznesini doğrudan yönetim rolüne bağlayın.","Kimlik oluştur","Sahip oluştur","Geçerli","Geçerli özne","Bu konsol isteğinde kullanılan yetki.","Geçerli oturum iptal edildi. Devam etmek için yeniden oturum açın.","Etkin yetkiyi, doğrudan OIDC kimliklerini, etkin yönetim oturumlarını ve kurtarma hazırlığını inceleyin.","Devre dışı bırak","Etkinleştir","Yönetişim","Doğrudan kimlikler","Kalıcı rol revizyonlarıyla tam yayımcı ve özne bağlamaları.","Kimlik ID","Kimlik revizyonu","Boşta kalma sonu","Giriş politikası","Geçersiz","Verilme zamanı","Yayımcı","Kimlik","Son görülme","Kimlik durumu yüklenemedi.","Yerel","Yerel sahip","Yerel sahip kimliği","Hayır","Değişiklik gerekmiyor.","Kullanılabilir doğrudan kimlik yok.","Etkin yönetim oturumu yok.","Özneniz bu kaynak için yetkili değil.","Yapılandırılmadı","İstenen kaynak bulunamadı.","Hazır değil","OIDC hazırlığı","Güvenli yapılandırma görünümü ve yetkilendirme dönemi.","Sayfa {page}","Parola","İzin reddedildi.","Etkin izinler","OIDC politikası ilerletildi; {count} oturum iptal edildi.","Kalıcı politika ilerletildi ancak anlık oturum temizliği tamamlanmadı.","Özne türü","Hazır","Kurtarma hazırlığı","Acil yerel sahip erişimi ve etkin giriş sınırı.","Yönlendirme URI'si","Kimlik durumunu yenile","Kimlik durumu yenilendi.","Kimlik işlemi tamamlanamadı.","İptal et","İptal edildi","Rol","Rol eşlemeleri","Rol kaynağı","Rolü kaydet","Değişiklikler kaydedildi.","Kapsamlar","Etkin oturumlar","Kimlik doğrulamayan başvurularla gösterilen sınırlı yönetim oturumları.","Kaynak başka yerde değişti. Geçerli değerleri inceleyip yeniden gönderin.","Özne","Kimlikler ve oturumlar","Kullanılamıyor","Güncelleme zamanı","Evet"],
    vi: ["Hết hạn tuyệt đối","Vô hiệu hóa phiên OIDC","Phương thức xác thực","Thế hệ phân quyền","Đã được cấp quyền","Bản sửa liên kết","Đã cấu hình thông tin xác thực máy khách","Bản sửa cấu hình","Xác nhận","Thao tác này tăng thế hệ phân quyền và vô hiệu hóa toàn bộ phiên OIDC. Tiếp tục?","Xác nhận thay đổi quản trị","Tắt danh tính {id}? Các phiên đang hoạt động của danh tính này sẽ không còn được phép xử lý yêu cầu.","Bật danh tính {id}?","Tạo liên kết chủ sở hữu? Chủ sở hữu có toàn quyền quản trị.","Thu hồi phiên của {id}?","Thu hồi phiên hiện tại? Bạn sẽ bị đăng xuất ngay lập tức.","Đổi {id} sang vai trò {role}? Các phiên hiện có sẽ bị vô hiệu hóa.","Tạo","Liên kết chính xác một nhà phát hành và chủ thể OIDC với vai trò quản trị trực tiếp.","Tạo danh tính","Tạo chủ sở hữu","Hiện tại","Chủ thể hiện tại","Quyền hạn được dùng cho yêu cầu console này.","Phiên hiện tại đã bị thu hồi. Hãy đăng nhập lại để tiếp tục.","Kiểm tra quyền hạn hiệu lực, danh tính OIDC trực tiếp, phiên quản trị đang hoạt động và trạng thái sẵn sàng khôi phục.","Tắt","Bật","Quản trị truy cập","Danh tính trực tiếp","Liên kết chính xác nhà phát hành và chủ thể với bản sửa vai trò bền vững.","ID danh tính","Bản sửa danh tính","Hết hạn do không hoạt động","Chính sách truy cập mạng","Không hợp lệ","Thời điểm cấp","Nhà phát hành","Danh tính","Hoạt động gần nhất","Không thể tải trạng thái danh tính.","Cục bộ","Chủ sở hữu cục bộ","Danh tính chủ sở hữu cục bộ","Không","Không cần thay đổi.","Không có danh tính trực tiếp.","Không có phiên quản trị đang hoạt động.","Chủ thể của bạn không được cấp quyền với tài nguyên này.","Chưa cấu hình","Không tìm thấy tài nguyên được yêu cầu.","Chưa sẵn sàng","Mức sẵn sàng OIDC","Thông tin cấu hình an toàn và thế hệ phân quyền.","Trang {page}","Mật khẩu","Quyền truy cập bị từ chối.","Quyền hiệu lực","Đã tăng chính sách OIDC; đã thu hồi {count} phiên.","Chính sách bền vững đã được tăng, nhưng việc dọn phiên tức thời chưa hoàn tất.","Loại chủ thể","Sẵn sàng","Mức sẵn sàng khôi phục","Quyền truy cập khẩn cấp của chủ sở hữu cục bộ và ranh giới mạng đang có hiệu lực.","URI chuyển hướng","Làm mới trạng thái danh tính","Đã làm mới trạng thái danh tính.","Không thể hoàn tất thao tác danh tính.","Thu hồi","Đã thu hồi","Vai trò","Ánh xạ vai trò","Nguồn vai trò","Lưu vai trò","Đã lưu thay đổi.","Phạm vi","Phiên đang hoạt động","Các phiên quản trị có giới hạn được biểu diễn bằng tham chiếu không thể dùng để xác thực.","Tài nguyên đã được thay đổi ở nơi khác. Hãy kiểm tra giá trị hiện tại rồi gửi lại.","Chủ thể","Danh tính và phiên","Không khả dụng","Cập nhật lúc","Có"],
};

const IDENTITY_SUPPLEMENTAL_LOCALE_VALUES = {
    "en": {"identity.already_exists": "An identity with this exact issuer and subject already exists.", "identity.governance": "Access & team"},
    "zh-CN": {"identity.already_exists": "已存在具有完全相同颁发者和主体的身份。"},
    "zh-TW": {"identity.already_exists": "已存在具有完全相同發行者與主體的身分。"},
    "de": {"identity.already_exists": "Eine Identität mit genau diesem Aussteller und Betreff ist bereits vorhanden."},
    "es": {"identity.already_exists": "Ya existe una identidad con este emisor y sujeto exactos."},
    "fr": {"identity.already_exists": "Une identité avec cet émetteur et ce sujet exacts existe déjà."},
    "id": {"identity.already_exists": "Identitas dengan penerbit dan subjek yang sama persis sudah ada."},
    "it": {"identity.already_exists": "Esiste già un'identità con questo emittente e soggetto esatti."},
    "ja": {"identity.already_exists": "この発行者とサブジェクトが完全に一致する ID は既に存在します。"},
    "ko": {"identity.already_exists": "이 발급자와 주체가 정확히 일치하는 ID가 이미 있습니다."},
    "pt": {"identity.already_exists": "Já existe uma identidade com este emissor e sujeito exatos."},
    "ru": {"identity.already_exists": "Идентичность с такими точными издателем и субъектом уже существует."},
    "th": {"identity.already_exists": "มีข้อมูลประจำตัวที่มีผู้ออกและหัวเรื่องตรงกันนี้อยู่แล้ว"},
    "tr": {"identity.already_exists": "Bu tam yayımcı ve özneye sahip bir kimlik zaten var."},
    "vi": {"identity.already_exists": "Đã tồn tại một danh tính có chính xác nhà phát hành và chủ thể này.", "identity.governance": "Truy cập và nhóm"}
};

const IDENTITY_ALIASES = {
    'identity.cancel': 'btn_cancel',
    'identity.close': 'btn_close',
    'identity.loading': 'loading',
    'identity.previous': 'previous',
    'identity.next': 'next',
    'identity.enabled': 'enabled',
    'identity.disabled': 'disabled',
    'identity.none': 'none',
    'identity.status': 'status',
    'identity.unknown': 'unknown',
};

const IDENTITY_LOCALE_TRANSLATIONS = Object.fromEntries(
    Object.entries(IDENTITY_LOCALE_VALUES).map(([locale, messages]) => [
        locale,
        Object.fromEntries(IDENTITY_KEYS.map((key, index) => [key, messages[index]]))
    ])
);

for (const [locale, messages] of Object.entries(IDENTITY_LOCALE_TRANSLATIONS)) {
    const catalog = getMessageCatalog(locale);
    for (const [target, source] of Object.entries(IDENTITY_ALIASES)) {
        messages[target] = TRANSLATIONS[locale]?.[source]
            || catalog[source]
            || TRANSLATIONS.en?.[source]
            || getMessageCatalog('en')[source]
            || source;
    }
    Object.assign(messages, IDENTITY_SUPPLEMENTAL_LOCALE_VALUES[locale]);
    Object.assign(PAGE_LOCALE_TRANSLATIONS[locale], messages);
}
