const OPERATIONAL_HEALTH_KEYS = [
    'slo.kicker', 'slo.title', 'slo.description', 'slo.loading', 'slo.rate',
    'slo.per_minute', 'slo.error_rate', 'slo.p95', 'slo.last_15_minutes',
    'slo.exhaustion', 'slo.bounded_sample', 'slo.route_health', 'slo.route',
    'slo.export_controls', 'slo.export_description', 'slo.runbooks', 'slo.enabled',
    'slo.disabled_default', 'slo.errors_of_requests', 'slo.sample_truncated',
    'slo.load_failed', 'slo.no_data', 'slo.status_healthy', 'slo.status_warning',
    'slo.status_critical', 'slo.status_no_data'
];

const OPERATIONAL_HEALTH_VALUES = {
    en: ["Service objectives","Operational health","Rate, errors, duration, route health, and capacity pressure from content-free request traces.","Loading","Request rate","per minute","Error rate","P95 duration","last 15 minutes","Exhaustion signals","bounded sample","Model-route health","Route","External telemetry","Exporters are disabled by default and never export prompt or response content.","Configuration and runbooks","Enabled","Disabled by default","{errors} errors / {requests} requests","Showing a bounded sample of {count} traces.","Operational health could not be loaded.","No traffic in this window.","Healthy","Warning","Critical","No data"],
    'zh-CN': ["服务目标","运行健康","通过不含内容的请求追踪查看速率、错误、耗时、路由健康与容量压力。","加载中","请求速率","每分钟","错误率","P95 耗时","最近 15 分钟","耗尽信号","有界样本","模型路由健康","路由","外部遥测","导出器默认关闭，且绝不导出提示词或响应内容。","配置与运行手册","已启用","默认关闭","{errors} 个错误 / {requests} 个请求","显示 {count} 条追踪的有界样本。","无法加载运行健康数据。","此时间窗口内没有流量。","健康","警告","严重","无数据"],
    'zh-TW': ["服務目標","運作健康","透過不含內容的請求追蹤查看速率、錯誤、延遲、路由健康與容量壓力。","載入中","請求速率","每分鐘","錯誤率","P95 延遲","最近 15 分鐘","耗盡訊號","有限樣本","模型路由健康","路由","外部遙測","匯出器預設關閉，且絕不匯出提示詞或回應內容。","設定與操作手冊","已啟用","預設關閉","{errors} 個錯誤 / {requests} 個請求","顯示 {count} 筆追蹤的有限樣本。","無法載入運作健康資料。","此時間範圍內沒有流量。","健康","警告","嚴重","無資料"],
    de: ["Serviceziele","Betriebszustand","Rate, Fehler, Dauer, Routenzustand und Kapazitätsdruck aus inhaltsfreien Anfrage-Traces.","Laden","Anfragerate","pro Minute","Fehlerrate","P95-Dauer","letzte 15 Minuten","Erschöpfungssignale","begrenzte Stichprobe","Modellrouten-Zustand","Route","Externe Telemetrie","Exporter sind standardmäßig deaktiviert und exportieren nie Prompt- oder Antwortinhalte.","Konfiguration und Runbooks","Aktiviert","Standardmäßig deaktiviert","{errors} Fehler / {requests} Anfragen","Begrenzte Stichprobe von {count} Traces.","Betriebszustand konnte nicht geladen werden.","Kein Datenverkehr in diesem Zeitraum.","Gesund","Warnung","Kritisch","Keine Daten"],
    es: ["Objetivos de servicio","Estado operativo","Tasa, errores, duración, salud de rutas y presión de capacidad desde trazas sin contenido.","Cargando","Tasa de solicitudes","por minuto","Tasa de errores","Duración P95","últimos 15 minutos","Señales de agotamiento","muestra acotada","Salud de rutas de modelo","Ruta","Telemetría externa","Los exportadores están desactivados por defecto y nunca exportan prompts ni respuestas.","Configuración y runbooks","Activado","Desactivado por defecto","{errors} errores / {requests} solicitudes","Muestra acotada de {count} trazas.","No se pudo cargar el estado operativo.","Sin tráfico en este intervalo.","Correcto","Advertencia","Crítico","Sin datos"],
    fr: ["Objectifs de service","Santé opérationnelle","Débit, erreurs, durée, santé des routes et pression de capacité issus de traces sans contenu.","Chargement","Débit de requêtes","par minute","Taux d’erreur","Durée P95","15 dernières minutes","Signaux d’épuisement","échantillon borné","Santé des routes de modèle","Route","Télémétrie externe","Les exportateurs sont désactivés par défaut et n’exportent jamais les prompts ni les réponses.","Configuration et procédures","Activé","Désactivé par défaut","{errors} erreurs / {requests} requêtes","Échantillon borné de {count} traces.","Impossible de charger la santé opérationnelle.","Aucun trafic sur cette période.","Sain","Avertissement","Critique","Aucune donnée"],
    id: ["Sasaran layanan","Kesehatan operasional","Laju, error, durasi, kesehatan rute, dan tekanan kapasitas dari jejak tanpa konten.","Memuat","Laju permintaan","per menit","Tingkat error","Durasi P95","15 menit terakhir","Sinyal kehabisan","sampel terbatas","Kesehatan rute model","Rute","Telemetri eksternal","Eksportir dinonaktifkan secara default dan tidak pernah mengekspor isi prompt atau respons.","Konfigurasi dan runbook","Aktif","Nonaktif secara default","{errors} error / {requests} permintaan","Menampilkan sampel terbatas dari {count} jejak.","Kesehatan operasional gagal dimuat.","Tidak ada trafik pada rentang ini.","Sehat","Peringatan","Kritis","Tidak ada data"],
    it: ["Obiettivi di servizio","Stato operativo","Frequenza, errori, durata, salute delle rotte e pressione di capacità da tracce senza contenuto.","Caricamento","Frequenza richieste","al minuto","Tasso di errore","Durata P95","ultimi 15 minuti","Segnali di esaurimento","campione limitato","Salute delle rotte modello","Rotta","Telemetria esterna","Gli exporter sono disattivati per impostazione predefinita e non esportano mai prompt o risposte.","Configurazione e runbook","Attivato","Disattivato per impostazione predefinita","{errors} errori / {requests} richieste","Campione limitato di {count} tracce.","Impossibile caricare lo stato operativo.","Nessun traffico in questa finestra.","Sano","Avviso","Critico","Nessun dato"],
    ja: ["サービス目標","運用状態","コンテンツを含まないトレースからレート、エラー、時間、ルート状態、容量圧力を表示します。","読み込み中","リクエスト率","毎分","エラー率","P95 時間","直近 15 分","枯渇シグナル","制限付きサンプル","モデルルートの状態","ルート","外部テレメトリ","エクスポーターは既定で無効で、プロンプトや応答内容を送信しません。","設定とランブック","有効","既定で無効","エラー {errors} / リクエスト {requests}","{count} トレースの制限付きサンプルです。","運用状態を読み込めませんでした。","この期間にトラフィックはありません。","正常","警告","重大","データなし"],
    ko: ["서비스 목표","운영 상태","콘텐츠 없는 요청 추적에서 요청률, 오류, 지연, 경로 상태 및 용량 압력을 표시합니다.","로드 중","요청률","분당","오류율","P95 지연","최근 15분","소진 신호","제한된 표본","모델 경로 상태","경로","외부 텔레메트리","내보내기는 기본적으로 비활성화되며 프롬프트나 응답 내용을 보내지 않습니다.","설정 및 런북","활성화","기본 비활성화","오류 {errors} / 요청 {requests}","{count}개 추적의 제한된 표본입니다.","운영 상태를 불러올 수 없습니다.","이 구간에 트래픽이 없습니다.","정상","경고","심각","데이터 없음"],
    pt: ["Objetivos de serviço","Saúde operacional","Taxa, erros, duração, saúde das rotas e pressão de capacidade a partir de rastreamentos sem conteúdo.","Carregando","Taxa de solicitações","por minuto","Taxa de erros","Duração P95","últimos 15 minutos","Sinais de esgotamento","amostra limitada","Saúde das rotas de modelo","Rota","Telemetria externa","Exportadores ficam desativados por padrão e nunca exportam prompts ou respostas.","Configuração e runbooks","Ativado","Desativado por padrão","{errors} erros / {requests} solicitações","Amostra limitada de {count} rastreamentos.","Não foi possível carregar a saúde operacional.","Sem tráfego neste período.","Saudável","Aviso","Crítico","Sem dados"],
    ru: ["Цели сервиса","Рабочее состояние","Частота, ошибки, длительность, состояние маршрутов и давление на ресурсы по трассировкам без содержимого.","Загрузка","Частота запросов","в минуту","Доля ошибок","Длительность P95","последние 15 минут","Сигналы исчерпания","ограниченная выборка","Состояние маршрутов моделей","Маршрут","Внешняя телеметрия","Экспорт отключён по умолчанию и никогда не передаёт содержимое запросов или ответов.","Настройка и инструкции","Включено","Отключено по умолчанию","{errors} ошибок / {requests} запросов","Ограниченная выборка: {count} трассировок.","Не удалось загрузить рабочее состояние.","Нет трафика в этом интервале.","Норма","Предупреждение","Критично","Нет данных"],
    th: ["เป้าหมายบริการ","สถานะการทำงาน","อัตรา ข้อผิดพลาด ระยะเวลา สุขภาพเส้นทาง และแรงกดดันความจุจากร่องรอยที่ไม่มีเนื้อหา","กำลังโหลด","อัตราคำขอ","ต่อนาที","อัตราข้อผิดพลาด","ระยะเวลา P95","15 นาทีล่าสุด","สัญญาณทรัพยากรหมด","ตัวอย่างแบบจำกัด","สุขภาพเส้นทางโมเดล","เส้นทาง","เทเลเมทรีภายนอก","ตัวส่งออกถูกปิดโดยค่าเริ่มต้นและไม่ส่งออกเนื้อหาพรอมต์หรือคำตอบ","การกำหนดค่าและคู่มือ","เปิดใช้","ปิดโดยค่าเริ่มต้น","ข้อผิดพลาด {errors} / คำขอ {requests}","แสดงตัวอย่างแบบจำกัด {count} ร่องรอย","โหลดสถานะการทำงานไม่ได้","ไม่มีทราฟฟิกในช่วงนี้","ปกติ","คำเตือน","วิกฤต","ไม่มีข้อมูล"],
    tr: ["Hizmet hedefleri","Operasyon sağlığı","İçeriksiz istek izlerinden hız, hata, süre, rota sağlığı ve kapasite baskısı.","Yükleniyor","İstek hızı","dakikada","Hata oranı","P95 süresi","son 15 dakika","Tükenme sinyalleri","sınırlı örnek","Model rota sağlığı","Rota","Harici telemetri","Dışa aktarıcılar varsayılan olarak kapalıdır ve istem veya yanıt içeriğini aktarmaz.","Yapılandırma ve çalışma kılavuzları","Etkin","Varsayılan olarak kapalı","{errors} hata / {requests} istek","{count} izden oluşan sınırlı örnek.","Operasyon sağlığı yüklenemedi.","Bu aralıkta trafik yok.","Sağlıklı","Uyarı","Kritik","Veri yok"],
    vi: ["Mục tiêu dịch vụ","Sức khỏe vận hành","Theo dõi tốc độ, lỗi, độ trễ, sức khỏe route và áp lực dung lượng từ dấu vết yêu cầu không chứa nội dung.","Đang tải","Tốc độ yêu cầu","mỗi phút","Tỷ lệ lỗi","Độ trễ P95","15 phút gần nhất","Tín hiệu cạn kiệt","mẫu có giới hạn","Sức khỏe route mô hình","Route","Telemetry bên ngoài","Các bộ xuất dữ liệu mặc định bị tắt và tuyệt đối không xuất nội dung prompt hoặc phản hồi.","Cấu hình và runbook","Đã bật","Mặc định tắt","{errors} lỗi / {requests} yêu cầu","Đang hiển thị mẫu có giới hạn gồm {count} dấu vết.","Không thể tải dữ liệu sức khỏe vận hành.","Không có lưu lượng trong khoảng thời gian này.","Ổn định","Cảnh báo","Nghiêm trọng","Chưa có dữ liệu"]
};

for (const [locale, values] of Object.entries(OPERATIONAL_HEALTH_VALUES)) {
    Object.assign(
        PAGE_LOCALE_TRANSLATIONS[locale],
        Object.fromEntries(OPERATIONAL_HEALTH_KEYS.map((key, index) => [key, values[index]])),
    );
}
