const TRACE_SHARED_LOCALE_KEYS = {
    'trace.observability': 'audit.observability', 'trace.export_jsonl': 'audit.export_jsonl',
    'trace.export_csv': 'audit.export_csv', 'trace.refresh': 'audit.refresh',
    'trace.filters': 'audit.filters', 'trace.outcome': 'audit.outcome', 'trace.all': 'audit.all',
    'trace.request_id': 'audit.request_id', 'trace.after': 'audit.after', 'trace.before': 'audit.before',
    'trace.apply': 'audit.apply', 'trace.clear': 'audit.clear', 'trace.previous': 'audit.previous',
    'trace.page': 'audit.page', 'trace.next': 'audit.next', 'trace.retention_days': 'audit.retention_days',
    'trace.save_retention': 'audit.save_retention',
    'trace.close': 'audit.close', 'trace.copy_request': 'audit.copy_request',
    'trace.pivot_request': 'audit.pivot_request', 'trace.unknown': 'audit.unknown',
    'trace.invalid_range': 'audit.invalid_range', 'trace.copied': 'audit.copied',
    'trace.copy_failed': 'audit.copy_failed', 'trace.exporting': 'audit.exporting',
    'trace.update_failed': 'audit.update_failed'
};

const TRACE_CONTEXT_KEYS = ['trace.details', 'trace.exported', 'trace.export_failed'];
const TRACE_CONTEXT_VALUES = {
    en: ["Trace details", "Trace export downloaded.", "Trace export could not be completed."],
    'zh-CN': ["追踪详情", "追踪导出已下载。", "无法完成追踪导出。"],
    'zh-TW': ["追蹤詳細資料", "追蹤匯出已下載。", "無法完成追蹤匯出。"],
    de: ["Trace-Details", "Trace-Export heruntergeladen.", "Trace-Export konnte nicht abgeschlossen werden."],
    es: ["Detalles de la traza", "Exportación de trazas descargada.", "No se pudo completar la exportación de trazas."],
    fr: ["Détails de la trace", "Export des traces téléchargé.", "Impossible de terminer l’export des traces."],
    id: ["Detail jejak", "Ekspor jejak telah diunduh.", "Ekspor jejak tidak dapat diselesaikan."],
    it: ["Dettagli traccia", "Esportazione tracce scaricata.", "Impossibile completare l’esportazione tracce."],
    ja: ["トレース詳細", "トレースのエクスポートをダウンロードしました。", "トレースのエクスポートを完了できませんでした。"],
    ko: ["추적 세부 정보", "추적 내보내기를 다운로드했습니다.", "추적 내보내기를 완료할 수 없습니다."],
    pt: ["Detalhes do rastreamento", "Exportação de rastreamentos baixada.", "Não foi possível concluir a exportação de rastreamentos."],
    ru: ["Сведения о трассировке", "Экспорт трассировок загружен.", "Не удалось завершить экспорт трассировок."],
    th: ["รายละเอียดการติดตาม", "ดาวน์โหลดข้อมูลการติดตามแล้ว", "ไม่สามารถส่งออกข้อมูลการติดตามได้"],
    tr: ["İz ayrıntıları", "İz dışa aktarımı indirildi.", "İz dışa aktarımı tamamlanamadı."],
    vi: ["Chi tiết dấu vết", "Đã tải bản xuất dấu vết.", "Không thể hoàn tất xuất dữ liệu dấu vết."]
};

const TRACE_KEYS = [
    'trace.title', 'trace.description', 'trace.filters_description', 'trace.protocol',
    'trace.provider', 'trace.model', 'trace.page_size', 'trace.safe_filter_hint',
    'trace.stream', 'trace.retention', 'trace.retention_description', 'trace.content_free',
    'trace.content_free_description', 'trace.max_traces', 'trace.diagnostic_only',
    'trace.raw_logs', 'trace.raw_logs_description', 'trace.started_at', 'trace.duration',
    'trace.status_code', 'trace.requested_model', 'trace.selected_provider', 'trace.tokens',
    'trace.cost', 'trace.decisions', 'trace.decisions_truncated', 'trace.attempt',
    'trace.tokens_short', 'trace.empty', 'trace.loading', 'trace.load_failed',
    'trace.detail_failed', 'trace.retention_confirm', 'trace.retention_updated'
];

const TRACE_LOCALE_VALUES = {
    en: ["Request traces","Explain routing, quality controls, fallbacks, failures, usage, and cost without storing prompts or responses.","Narrow the decision stream by protocol, outcome, route, and correlation ID.","Protocol","Provider","Model","Traces per page","Only protocol, outcome, and page size are remembered. Provider, model, request ID, and time bounds remain session-only.","Decision stream","Trace retention","Traces are pruned independently when either the age or count limit is exceeded.","Content-free by design","Only allowlisted decisions and numeric usage are stored—never prompts, responses, secrets, or exception text.","Maximum traces","Diagnostic only","Bounded raw logs","Use request traces first. This independently retained, redacted text stream is intended for low-level runtime diagnosis.","Started at","Duration","Status code","Requested model","Selected provider","Tokens (input / output / total)","Estimated cost","Ordered decisions","The decision limit was reached; later decisions were intentionally omitted.","Attempt","tokens","No request traces match these filters.","Loading request traces…","Request traces could not be loaded.","Trace details could not be loaded.","Save {days} days and {maxTraces} traces? Traces outside either limit may be removed immediately.","Retention saved. {count} traces were removed."],
    'zh-CN': ["请求追踪","在不存储提示词或响应的前提下，解释路由、质量控制、回退、故障、用量和成本。","按协议、结果、路由和关联 ID 缩小决策流。","协议","提供商","模型","每页追踪数","仅记住协议、结果和每页数量。提供商、模型、请求 ID 与时间范围仅在本次会话中保留。","决策流","追踪保留策略","追踪会独立清理，只要超过时间或数量上限。","设计上不含内容","仅存储白名单决策与数值用量，绝不存储提示词、响应、密钥或异常文本。","最大追踪数","仅用于诊断","有界原始日志","请优先使用请求追踪。这个独立保留且已脱敏的文本流用于底层运行诊断。","开始时间","耗时","状态码","请求的模型","选定的提供商","令牌（输入 / 输出 / 总计）","预估成本","有序决策","已达到决策上限，后续决策已按设计省略。","尝试","令牌","没有符合筛选条件的请求追踪。","正在加载请求追踪…","无法加载请求追踪。","无法加载追踪详情。","保存 {days} 天和 {maxTraces} 条追踪吗？超出任一限制的追踪可能会立即删除。","保留策略已保存，删除了 {count} 条追踪。"],
    'zh-TW': ["請求追蹤","在不儲存提示詞或回應的前提下，說明路由、品質控制、備援、故障、用量與成本。","依協定、結果、路由和關聯 ID 縮小決策串流。","協定","供應商","模型","每頁追蹤數","只會記住協定、結果與每頁數量。供應商、模型、請求 ID 和時間範圍僅保留於本次工作階段。","決策串流","追蹤保留政策","追蹤會獨立清除，只要超過時間或數量上限。","設計上不含內容","只儲存允許的決策與數值用量，絕不儲存提示詞、回應、密鑰或例外文字。","追蹤數上限","僅供診斷","有限原始記錄","請優先使用請求追蹤。此獨立保留且已遮蔽的文字串流用於底層執行診斷。","開始時間","持續時間","狀態碼","要求的模型","選定的供應商","權杖（輸入 / 輸出 / 總計）","預估成本","依序決策","已達決策上限，後續決策已刻意省略。","嘗試","權杖","沒有符合篩選條件的請求追蹤。","正在載入請求追蹤…","無法載入請求追蹤。","無法載入追蹤詳細資料。","要儲存 {days} 天與 {maxTraces} 筆追蹤嗎？超出任一限制的追蹤可能會立即移除。","保留政策已儲存，已移除 {count} 筆追蹤。"],
    de: ["Anfrage-Traces","Erklärt Routing, Qualitätskontrollen, Fallbacks, Fehler, Nutzung und Kosten, ohne Prompts oder Antworten zu speichern.","Den Entscheidungsstrom nach Protokoll, Ergebnis, Route und Korrelations-ID eingrenzen.","Protokoll","Anbieter","Modell","Traces pro Seite","Nur Protokoll, Ergebnis und Seitengröße werden gespeichert. Anbieter, Modell, Anfrage-ID und Zeitraum bleiben sitzungsbezogen.","Entscheidungsstrom","Trace-Aufbewahrung","Traces werden unabhängig bereinigt, sobald die Alters- oder Anzahlgrenze überschritten ist.","Inhaltsfrei konzipiert","Gespeichert werden nur erlaubte Entscheidungen und numerische Nutzung – niemals Prompts, Antworten, Geheimnisse oder Ausnahmetext.","Maximale Traces","Nur Diagnose","Begrenzte Rohprotokolle","Verwenden Sie zuerst Anfrage-Traces. Dieser separat gespeicherte, redigierte Textstrom dient der technischen Laufzeitdiagnose.","Gestartet um","Dauer","Statuscode","Angefordertes Modell","Gewählter Anbieter","Token (Eingabe / Ausgabe / Gesamt)","Geschätzte Kosten","Geordnete Entscheidungen","Das Entscheidungslimit wurde erreicht; spätere Entscheidungen wurden absichtlich ausgelassen.","Versuch","Token","Keine Anfrage-Traces entsprechen diesen Filtern.","Anfrage-Traces werden geladen…","Anfrage-Traces konnten nicht geladen werden.","Trace-Details konnten nicht geladen werden.","{days} Tage und {maxTraces} Traces speichern? Traces außerhalb einer Grenze können sofort entfernt werden.","Aufbewahrung gespeichert. {count} Traces wurden entfernt."],
    es: ["Trazas de solicitudes","Explica el enrutamiento, los controles de calidad, las alternativas, los fallos, el uso y el coste sin guardar prompts ni respuestas.","Acota el flujo de decisiones por protocolo, resultado, ruta e ID de correlación.","Protocolo","Proveedor","Modelo","Trazas por página","Solo se recuerdan el protocolo, el resultado y el tamaño de página. El proveedor, el modelo, el ID de solicitud y el intervalo quedan en la sesión.","Flujo de decisiones","Retención de trazas","Las trazas se eliminan de forma independiente al superar el límite de antigüedad o cantidad.","Sin contenido por diseño","Solo se guardan decisiones permitidas y uso numérico; nunca prompts, respuestas, secretos ni texto de excepciones.","Máximo de trazas","Solo diagnóstico","Registros sin procesar limitados","Usa primero las trazas. Este flujo de texto redactado y con retención independiente sirve para diagnóstico técnico del entorno.","Inicio","Duración","Código de estado","Modelo solicitado","Proveedor seleccionado","Tokens (entrada / salida / total)","Coste estimado","Decisiones ordenadas","Se alcanzó el límite de decisiones; las posteriores se omitieron intencionadamente.","Intento","tokens","Ninguna traza coincide con estos filtros.","Cargando trazas de solicitudes…","No se pudieron cargar las trazas.","No se pudieron cargar los detalles de la traza.","¿Guardar {days} días y {maxTraces} trazas? Las trazas fuera de cualquier límite pueden eliminarse de inmediato.","Retención guardada. Se eliminaron {count} trazas."],
    fr: ["Traces de requêtes","Expliquez le routage, les contrôles qualité, les replis, les échecs, l’usage et le coût sans stocker les prompts ni les réponses.","Affinez le flux de décisions par protocole, résultat, route et ID de corrélation.","Protocole","Fournisseur","Modèle","Traces par page","Seuls le protocole, le résultat et la taille de page sont mémorisés. Le fournisseur, le modèle, l’ID de requête et la période restent limités à la session.","Flux de décisions","Conservation des traces","Les traces sont purgées indépendamment dès que la limite d’âge ou de nombre est dépassée.","Sans contenu par conception","Seules les décisions autorisées et les données d’usage numériques sont stockées — jamais les prompts, réponses, secrets ou textes d’exception.","Nombre maximal de traces","Diagnostic uniquement","Journaux bruts limités","Utilisez d’abord les traces. Ce flux de texte expurgé et conservé séparément sert au diagnostic technique de l’exécution.","Démarré à","Durée","Code d’état","Modèle demandé","Fournisseur sélectionné","Jetons (entrée / sortie / total)","Coût estimé","Décisions ordonnées","La limite de décisions est atteinte ; les décisions suivantes ont été volontairement omises.","Tentative","jetons","Aucune trace ne correspond à ces filtres.","Chargement des traces…","Impossible de charger les traces.","Impossible de charger les détails de la trace.","Enregistrer {days} jours et {maxTraces} traces ? Les traces hors de l’une des limites peuvent être supprimées immédiatement.","Conservation enregistrée. {count} traces ont été supprimées."],
    id: ["Jejak permintaan","Jelaskan perutean, kontrol kualitas, fallback, kegagalan, penggunaan, dan biaya tanpa menyimpan prompt atau respons.","Persempit aliran keputusan berdasarkan protokol, hasil, rute, dan ID korelasi.","Protokol","Penyedia","Model","Jejak per halaman","Hanya protokol, hasil, dan ukuran halaman yang diingat. Penyedia, model, ID permintaan, dan batas waktu hanya berlaku selama sesi.","Aliran keputusan","Retensi jejak","Jejak dipangkas secara terpisah saat batas usia atau jumlah terlampaui.","Tanpa konten sejak desain","Hanya keputusan yang diizinkan dan penggunaan numerik yang disimpan—bukan prompt, respons, rahasia, atau teks pengecualian.","Jejak maksimum","Hanya diagnostik","Log mentah terbatas","Gunakan jejak permintaan terlebih dahulu. Aliran teks tersensor dengan retensi terpisah ini untuk diagnosis runtime tingkat rendah.","Dimulai pada","Durasi","Kode status","Model yang diminta","Penyedia terpilih","Token (masukan / keluaran / total)","Perkiraan biaya","Keputusan berurutan","Batas keputusan tercapai; keputusan berikutnya sengaja dihilangkan.","Percobaan","token","Tidak ada jejak permintaan yang cocok dengan filter ini.","Memuat jejak permintaan…","Jejak permintaan tidak dapat dimuat.","Detail jejak tidak dapat dimuat.","Simpan {days} hari dan {maxTraces} jejak? Jejak di luar salah satu batas dapat langsung dihapus.","Retensi disimpan. {count} jejak dihapus."],
    it: ["Tracce delle richieste","Spiega instradamento, controlli di qualità, fallback, errori, utilizzo e costi senza memorizzare prompt o risposte.","Restringi il flusso decisionale per protocollo, esito, percorso e ID di correlazione.","Protocollo","Provider","Modello","Tracce per pagina","Vengono ricordati solo protocollo, esito e dimensione pagina. Provider, modello, ID richiesta e periodo restano nella sessione.","Flusso decisionale","Conservazione tracce","Le tracce vengono eliminate separatamente quando si supera il limite di età o quantità.","Senza contenuti per progettazione","Vengono memorizzate solo decisioni consentite e utilizzo numerico, mai prompt, risposte, segreti o testo delle eccezioni.","Numero massimo di tracce","Solo diagnostica","Log grezzi limitati","Usa prima le tracce. Questo flusso di testo oscurato e conservato separatamente serve alla diagnostica tecnica del runtime.","Ora di avvio","Durata","Codice di stato","Modello richiesto","Provider selezionato","Token (input / output / totale)","Costo stimato","Decisioni ordinate","È stato raggiunto il limite di decisioni; quelle successive sono state omesse intenzionalmente.","Tentativo","token","Nessuna traccia corrisponde a questi filtri.","Caricamento tracce…","Impossibile caricare le tracce.","Impossibile caricare i dettagli della traccia.","Salvare {days} giorni e {maxTraces} tracce? Le tracce oltre uno dei limiti possono essere rimosse subito.","Conservazione salvata. Rimosse {count} tracce."],
    ja: ["リクエストトレース","プロンプトや応答を保存せずに、ルーティング、品質制御、フォールバック、障害、使用量、コストを説明します。","プロトコル、結果、ルート、相関 ID で意思決定ストリームを絞り込みます。","プロトコル","プロバイダー","モデル","1 ページのトレース数","記憶されるのはプロトコル、結果、ページサイズだけです。プロバイダー、モデル、リクエスト ID、期間はセッション内にのみ保持されます。","意思決定ストリーム","トレース保持","経過日数または件数の上限を超えたトレースは個別に削除されます。","設計上コンテンツを保存しません","許可された意思決定と数値使用量のみを保存し、プロンプト、応答、秘密情報、例外文は保存しません。","最大トレース数","診断専用","制限付き生ログ","まずリクエストトレースを使用してください。別途保持されるマスキング済みテキストストリームは低レベルの実行診断用です。","開始日時","所要時間","ステータスコード","要求モデル","選択プロバイダー","トークン（入力 / 出力 / 合計）","推定コスト","順序付き意思決定","意思決定の上限に達したため、以降は意図的に省略されました。","試行","トークン","このフィルターに一致するトレースはありません。","リクエストトレースを読み込み中…","リクエストトレースを読み込めませんでした。","トレース詳細を読み込めませんでした。","{days} 日、{maxTraces} 件で保存しますか？いずれかの上限を超えたトレースは直ちに削除される場合があります。","保持設定を保存しました。{count} 件のトレースを削除しました。"],
    ko: ["요청 추적","프롬프트나 응답을 저장하지 않고 라우팅, 품질 제어, 대체 경로, 오류, 사용량 및 비용을 설명합니다.","프로토콜, 결과, 경로 및 상관 ID로 의사결정 흐름을 좁힙니다.","프로토콜","제공자","모델","페이지당 추적","프로토콜, 결과, 페이지 크기만 기억됩니다. 제공자, 모델, 요청 ID 및 시간 범위는 세션에만 유지됩니다.","의사결정 흐름","추적 보존","기간 또는 개수 제한을 넘으면 추적이 별도로 정리됩니다.","설계상 콘텐츠 미저장","허용된 결정과 수치 사용량만 저장하며 프롬프트, 응답, 비밀 또는 예외 텍스트는 저장하지 않습니다.","최대 추적 수","진단 전용","제한된 원시 로그","요청 추적을 먼저 사용하세요. 별도로 보존되는 마스킹된 텍스트 흐름은 저수준 런타임 진단용입니다.","시작 시각","기간","상태 코드","요청 모델","선택된 제공자","토큰(입력 / 출력 / 합계)","예상 비용","순서가 있는 결정","결정 한도에 도달하여 이후 결정은 의도적으로 생략되었습니다.","시도","토큰","이 필터와 일치하는 요청 추적이 없습니다.","요청 추적 로드 중…","요청 추적을 불러올 수 없습니다.","추적 세부 정보를 불러올 수 없습니다.","{days}일 및 {maxTraces}개 추적으로 저장할까요? 한도를 벗어난 추적은 즉시 제거될 수 있습니다.","보존 정책을 저장했습니다. {count}개 추적을 제거했습니다."],
    pt: ["Rastreamentos de solicitações","Explique roteamento, controles de qualidade, alternativas, falhas, uso e custo sem armazenar prompts ou respostas.","Restrinja o fluxo de decisões por protocolo, resultado, rota e ID de correlação.","Protocolo","Provedor","Modelo","Rastreamentos por página","Apenas protocolo, resultado e tamanho da página são lembrados. Provedor, modelo, ID da solicitação e período ficam somente na sessão.","Fluxo de decisões","Retenção de rastreamentos","Os rastreamentos são removidos separadamente quando o limite de idade ou quantidade é excedido.","Sem conteúdo por definição","Somente decisões permitidas e uso numérico são armazenados — nunca prompts, respostas, segredos ou texto de exceções.","Máximo de rastreamentos","Somente diagnóstico","Logs brutos limitados","Use primeiro os rastreamentos. Este fluxo de texto ocultado e retido separadamente destina-se ao diagnóstico técnico do ambiente.","Iniciado em","Duração","Código de status","Modelo solicitado","Provedor selecionado","Tokens (entrada / saída / total)","Custo estimado","Decisões ordenadas","O limite de decisões foi atingido; as decisões posteriores foram omitidas intencionalmente.","Tentativa","tokens","Nenhum rastreamento corresponde a estes filtros.","Carregando rastreamentos…","Não foi possível carregar os rastreamentos.","Não foi possível carregar os detalhes do rastreamento.","Salvar {days} dias e {maxTraces} rastreamentos? Rastreamentos fora de qualquer limite podem ser removidos imediatamente.","Retenção salva. {count} rastreamentos foram removidos."],
    ru: ["Трассировки запросов","Объясняет маршрутизацию, контроль качества, резервные варианты, сбои, использование и стоимость без хранения промптов или ответов.","Ограничьте поток решений по протоколу, результату, маршруту и ID корреляции.","Протокол","Провайдер","Модель","Трассировок на странице","Запоминаются только протокол, результат и размер страницы. Провайдер, модель, ID запроса и временной диапазон сохраняются лишь в сеансе.","Поток решений","Хранение трассировок","Трассировки удаляются отдельно при превышении ограничения по возрасту или количеству.","Без содержимого по замыслу","Хранятся только разрешённые решения и числовые данные использования — без промптов, ответов, секретов и текста исключений.","Максимум трассировок","Только диагностика","Ограниченные необработанные журналы","Сначала используйте трассировки. Этот отдельно хранимый обезличенный текстовый поток предназначен для низкоуровневой диагностики среды.","Время начала","Длительность","Код состояния","Запрошенная модель","Выбранный провайдер","Токены (ввод / вывод / всего)","Оценочная стоимость","Упорядоченные решения","Достигнут предел решений; последующие решения намеренно опущены.","Попытка","токенов","Нет трассировок, соответствующих этим фильтрам.","Загрузка трассировок…","Не удалось загрузить трассировки.","Не удалось загрузить сведения о трассировке.","Сохранить {days} дней и {maxTraces} трассировок? Трассировки вне любого предела могут быть удалены сразу.","Политика сохранена. Удалено трассировок: {count}."],
    th: ["การติดตามคำขอ","อธิบายการกำหนดเส้นทาง การควบคุมคุณภาพ ทางเลือกสำรอง ความล้มเหลว การใช้งาน และค่าใช้จ่ายโดยไม่เก็บพรอมต์หรือคำตอบ","จำกัดสตรีมการตัดสินใจตามโปรโตคอล ผลลัพธ์ เส้นทาง และรหัสความสัมพันธ์","โปรโตคอล","ผู้ให้บริการ","โมเดล","การติดตามต่อหน้า","ระบบจะจำเฉพาะโปรโตคอล ผลลัพธ์ และขนาดหน้า ผู้ให้บริการ โมเดล รหัสคำขอ และช่วงเวลาจะอยู่เฉพาะในเซสชัน","สตรีมการตัดสินใจ","การเก็บการติดตาม","การติดตามจะถูกล้างแยกต่างหากเมื่อเกินขีดจำกัดอายุหรือจำนวน","ออกแบบให้ไม่มีเนื้อหา","จัดเก็บเฉพาะการตัดสินใจที่อนุญาตและตัวเลขการใช้งาน ไม่เก็บพรอมต์ คำตอบ ความลับ หรือข้อความข้อยกเว้น","จำนวนการติดตามสูงสุด","สำหรับวินิจฉัยเท่านั้น","บันทึกดิบแบบจำกัด","ใช้การติดตามคำขอก่อน สตรีมข้อความที่ปกปิดข้อมูลและเก็บแยกนี้มีไว้สำหรับวินิจฉัยรันไทม์ระดับล่าง","เวลาเริ่ม","ระยะเวลา","รหัสสถานะ","โมเดลที่ขอ","ผู้ให้บริการที่เลือก","โทเค็น (ขาเข้า / ขาออก / รวม)","ค่าใช้จ่ายโดยประมาณ","การตัดสินใจตามลำดับ","ถึงขีดจำกัดการตัดสินใจแล้ว รายการถัดไปจึงถูกละไว้โดยตั้งใจ","ครั้งที่ลอง","โทเค็น","ไม่มีการติดตามคำขอที่ตรงกับตัวกรองเหล่านี้","กำลังโหลดการติดตามคำขอ…","ไม่สามารถโหลดการติดตามคำขอได้","ไม่สามารถโหลดรายละเอียดการติดตามได้","บันทึก {days} วันและ {maxTraces} การติดตามหรือไม่ รายการที่เกินขีดจำกัดใดขีดจำกัดหนึ่งอาจถูกลบทันที","บันทึกการเก็บรักษาแล้ว ลบ {count} การติดตาม"],
    tr: ["İstek izleri","İstemleri veya yanıtları saklamadan yönlendirme, kalite denetimleri, yedek yollar, hatalar, kullanım ve maliyeti açıklayın.","Karar akışını protokol, sonuç, rota ve ilişkilendirme kimliğiyle daraltın.","Protokol","Sağlayıcı","Model","Sayfa başına iz","Yalnızca protokol, sonuç ve sayfa boyutu hatırlanır. Sağlayıcı, model, istek kimliği ve zaman aralığı yalnızca oturumda kalır.","Karar akışı","İz saklama","Yaş veya sayı sınırı aşıldığında izler bağımsız olarak temizlenir.","Tasarım gereği içeriksiz","Yalnızca izin verilen kararlar ve sayısal kullanım saklanır; istemler, yanıtlar, sırlar veya istisna metinleri asla saklanmaz.","En fazla iz","Yalnızca tanılama","Sınırlı ham günlükler","Önce istek izlerini kullanın. Ayrı saklanan ve gizlenmiş bu metin akışı düşük düzey çalışma zamanı tanılaması içindir.","Başlangıç zamanı","Süre","Durum kodu","İstenen model","Seçilen sağlayıcı","Token (girdi / çıktı / toplam)","Tahmini maliyet","Sıralı kararlar","Karar sınırına ulaşıldı; sonraki kararlar bilinçli olarak atlandı.","Deneme","token","Bu filtrelerle eşleşen istek izi yok.","İstek izleri yükleniyor…","İstek izleri yüklenemedi.","İz ayrıntıları yüklenemedi.","{days} gün ve {maxTraces} iz kaydedilsin mi? Sınırların dışındaki izler hemen kaldırılabilir.","Saklama kaydedildi. {count} iz kaldırıldı."],
    vi: ["Dấu vết yêu cầu","Giải thích định tuyến, kiểm soát chất lượng, chuyển dự phòng, lỗi, mức sử dụng và chi phí mà không lưu prompt hoặc phản hồi.","Thu hẹp luồng quyết định theo giao thức, kết quả, tuyến xử lý và ID tương quan.","Giao thức","Nhà cung cấp","Mô hình","Dấu vết mỗi trang","Chỉ ghi nhớ giao thức, kết quả và kích thước trang. Nhà cung cấp, mô hình, ID yêu cầu và mốc thời gian chỉ tồn tại trong phiên.","Luồng quyết định","Lưu giữ dấu vết","Dấu vết được dọn độc lập khi vượt quá giới hạn thời gian hoặc số lượng.","Không lưu nội dung ngay từ thiết kế","Chỉ lưu quyết định trong danh sách cho phép và số liệu sử dụng; tuyệt đối không lưu prompt, phản hồi, bí mật hoặc nội dung ngoại lệ.","Số dấu vết tối đa","Chỉ dùng để chẩn đoán","Nhật ký thô có giới hạn","Hãy dùng dấu vết yêu cầu trước. Luồng văn bản đã che dữ liệu và được lưu riêng này chỉ dành cho chẩn đoán runtime cấp thấp.","Thời điểm bắt đầu","Thời lượng","Mã trạng thái","Mô hình được yêu cầu","Nhà cung cấp được chọn","Token (đầu vào / đầu ra / tổng)","Chi phí ước tính","Các quyết định theo thứ tự","Đã đạt giới hạn quyết định; các quyết định sau đó được chủ động lược bỏ.","Lần thử","token","Không có dấu vết yêu cầu phù hợp với các bộ lọc này.","Đang tải dấu vết yêu cầu…","Không thể tải dấu vết yêu cầu.","Không thể tải chi tiết dấu vết.","Lưu {days} ngày và {maxTraces} dấu vết? Các dấu vết vượt một trong hai giới hạn có thể bị xóa ngay lập tức.","Đã lưu chính sách. Đã xóa {count} dấu vết."]
};

for (const [locale, values] of Object.entries(TRACE_LOCALE_VALUES)) {
    const messages = Object.fromEntries(TRACE_KEYS.map((key, index) => [key, values[index]]));
    Object.assign(messages, Object.fromEntries(TRACE_CONTEXT_KEYS.map((key, index) => [key, TRACE_CONTEXT_VALUES[locale][index]])));
    for (const [traceKey, auditKey] of Object.entries(TRACE_SHARED_LOCALE_KEYS)) messages[traceKey] = PAGE_LOCALE_TRANSLATIONS[locale][auditKey];
    Object.assign(PAGE_LOCALE_TRANSLATIONS[locale], messages);
}
