"""Check or print the environment reference generated by the runtime schema."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
REFERENCE = ROOT / "docs/reference/configuration.md"
if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from core.configuration_schema import environment_reference  # noqa: E402


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args(arguments)
    generated = environment_reference()
    if not options.check:
        print(generated, end="")
        return 0
    if not REFERENCE.exists() or REFERENCE.read_text(encoding="utf-8") != generated:
        print(
            "docs/reference/configuration.md is stale; regenerate it from "
            "backend/core/configuration_schema.py.",
            file=sys.stderr,
        )
        return 1
    print("Configuration reference is current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
